Create tracking_chain-milestone_4.md
w3f/Grant-Milestone-Delivery pull request #1039
Opened 2023-10-26 08:13 UTC by FedeC87p

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] This pull request is being made by the same account as the accepted application.
- [X] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [X] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1847

2023-11-01 20:20 UTC, keeganquigley commented
Thanks for the delivery @FedeC87p someone will look at it shortly.

2023-11-06 22:34 UTC, takahser commented
@FedeC87p sorry for the delay here; we've a bit of a backlog currently. Just FYI, I'm working on the evaluation and I'll be back with more feedback soon.

2023-11-07 09:01 UTC, FedeC87p commented
> @FedeC87p sorry for the delay here; we've a bit of a backlog currently. Just FYI, I'm working on the evaluation and I'll be back with more feedback soon.

Don't worry, there's no problem.

2023-11-08 10:05 UTC, takahser requested changes
@FedeC87p thanks for your patience, I added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/400344ddc60245673d2af371eb6873d59f34a479/evaluations/tracking_chain_4_takahser.md). Don't hesitate to ask questions, if anything is unclear.

2023-11-08 10:20 UTC, FedeC87p commented
> @FedeC87p thanks for your patience, I added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/400344ddc60245673d2af371eb6873d59f34a479/evaluations/tracking_chain_4_takahser.md). Don't hesitate to ask questions, if anything is unclear.

Hi,   
yes, for those who have never used TrackingChain it is probably best to start from the Step by Step guide:  
https://github.com/TrackingChains/TrackingChain/wiki/Configuration-Step-By-Step  
  
Furthermore, you can find the generic guide where all the features of the program are explained:  
https://github.com/TrackingChains/TrackingChain/wiki  

The docker compose allows you to replace many of the Step By Step operations, as it automatically loads all the services with the configurations and a pre SEED of the data in order to provide a ready-to-use application for different chains (Rococo Contract, Shibuya Ink , Shibuya EVM, MoonBase EVM).

2023-11-08 10:29 UTC, takahser commented
@FedeC87p Do I have to go through the whole guide to test the functionality of M4 or is there a shortcut?

> The docker compose allows you to replace many of the Step By Step operations, as it automatically loads all the services with the configurations and a pre SEED of the data in order to provide a ready-to-use application for different chains (Rococo Contract, Shibuya Ink , Shibuya EVM, MoonBase EVM).

While I appreciate your explanations I didn't quite get how they're relevant to the errors.

2023-11-08 10:31 UTC, FedeC87p commented
DockerCompose, the error is due to the first launch (as the services are running queries while the database is still being loaded), it is described in the link below. 

https://github.com/TrackingChains/TrackingChain/wiki/Docker-Compose  
  
I modified the docs to point directly to the project file

2023-11-08 10:34 UTC, FedeC87p commented
No, in my opinion you can start docker, which already has everything you need. (The errors that docker gives are temporary, so you can ignore them and restart any services if they were shut down due to the initial error).

In my opinion, once you start docker, just follow this guide:
https://github.com/TrackingChains/TrackingChain/wiki/Demo-Step-By-Step

Here you can upload an onchain data and then verify Milestone 4

If it is useful, I am also available for a video call

2023-11-08 10:37 UTC, takahser commented
@FedeC87p thanks for the offer, I think a video call might make sense and accelerate the evaluation process. Feel free to book a slot [here](https://calendar.app.google/w2m14bZyjpB2Afuq6).

> In the next versions a checker will be inserted to wait for the complete loading of the sql server.

Regarding this, is there any reason not to do it now already? AFAIK you can [make services dependent on each other](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) with docker compose.

2023-11-09 13:27 UTC, takahser commented
@FedeC87p thanks for your time today. As discussed, I've updated the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/e5d8a8bc01001cb679991f351d3d994d63a8f00f/evaluations/tracking_chain_4_takahser.md) - the only thing missing is the resolution of the docker-compose startup bug.

2023-11-09 14:05 UTC, FedeC87p commented
@takahser thanks for the support.

I solved it by adding a check on each worker to check if the database is ready, this way it will only start the jobs in that case.

This way I can prevent even cases where you are not using Docker.

At most from the logs you will be able to find only one database access error (which is what is done to check if the database is ready).

You can already test the behavior by running docker-compose up

2023-11-14 15:15 UTC, takahser commented
@FedeC87p sorry for the delay here. I've pulled the latest changes (69742af590942439e95adab80cfe458f7637aa8e) and tried again, but I'm still getting the `SqlException`s and `InvalidOperationException`s. Note that I've removed the old containers and images before running `docker compose up`.

```bash
% docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                      docker:desktop-linux
[+] Running 8/5
 ✔ Container trackingchain-trackingdb-1                                                                                                                      Created                         0.0s 
 ! trackingdb The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                 0.0s 
 ✔ Container trackingchain-triage-1                                                                                                                          Created                         0.0s 
 ✔ Container trackingchain-webapp-1                                                                                                                          Created                         0.0s 
 ✔ Container trackingchain-aggregator-pool-1                                                                                                                 Created                         0.0s 
 ✔ Container trackingchain-transaction-generator-1                                                                                                           Created                         0.0s 
 ✔ Container trackingchain-transaction-watcher-1                                                                                                             Created                         0.0s 
 ✔ Container trackingchain-monitor-1                                                                                                                         Created                         0.0s 
Attaching to trackingchain-aggregator-pool-1, trackingchain-monitor-1, trackingchain-trackingdb-1, trackingchain-transaction-generator-1, trackingchain-transaction-watcher-1, trackingchain-triage-1, trackingchain-webapp-1
trackingchain-trackingdb-1             | SQL Server 2022 will run as non-root by default.
trackingchain-trackingdb-1             | This container is running as user mssql.
trackingchain-trackingdb-1             | To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
trackingchain-webapp-1                 | [15:09:28.135  WRN][]: Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.  Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository 
trackingchain-triage-1                 | [15:09:28.152  INF][]: Migration Db Worker running.  TrackingChain.TriageAPI.HostedService.MigratorDBHostedService 
trackingchain-webapp-1                 | [15:09:28.247  WRN][]: No XML encryptor configured. Key {6f6e6e77-8b98-4203-90c0-3c5a0c7a0b00} may be persisted to storage in unencrypted form.  Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager 
trackingchain-webapp-1                 | [15:09:28.291  WRN][]: Overriding address(es) 'http://+:80'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.  Microsoft.AspNetCore.Server.Kestrel 
trackingchain-webapp-1                 | [15:09:28.302  INF][]: Now listening on: http://0.0.0.0:12345  Microsoft.Hosting.Lifetime 
trackingchain-webapp-1                 | [15:09:28.302  INF][]: Application started. Press Ctrl+C to shut down.  Microsoft.Hosting.Lifetime 
trackingchain-webapp-1                 | [15:09:28.302  INF][]: Hosting environment: Production  Microsoft.Hosting.Lifetime 
trackingchain-webapp-1                 | [15:09:28.302  INF][]: Content root path: /app  Microsoft.Hosting.Lifetime 
trackingchain-aggregator-pool-1        | [15:09:28.562  WRN][]: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.  Microsoft.EntityFrameworkCore.Query 
trackingchain-transaction-generator-1  | [15:09:28.657  WRN][]: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.  Microsoft.EntityFrameworkCore.Query 
trackingchain-transaction-watcher-1    | [15:09:28.775  WRN][]: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.  Microsoft.EntityFrameworkCore.Query 
trackingchain-monitor-1                | [15:09:28.920  WRN][]: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.  Microsoft.EntityFrameworkCore.Query 
trackingchain-trackingdb-1             | 2023-11-14 15:09:31.69 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2023-11-14 15:09:31.72 Server      Did not find an existing master data file /var/opt/mssql/data/master.mdf, copying the missing default master and other system database files. If you have moved the database location, but not moved the database files, startup may fail. To repair: shutdown SQL Server, move the master database to configured location, and restart.
2023-11-14 15:09:31.72 Server      Setup step is copying system data file 'C:\templatedata\mastlog.ldf' to '/var/opt/mssql/data/mastlog.ldf'.
2023-11-14 15:09:31.73 Server      Setup step is copying system data file 'C:\templatedata\model.mdf' to '/var/opt/mssql/data/model.mdf'.
2023-11-14 15:09:31.73 Server      Setup step is copying system data file 'C:\templatedata\modellog.ldf' to '/var/opt/mssql/data/modellog.ldf'.
2023-11-14 15:09:31.74 Server      Setup step is copying system data file 'C:\templatedata\msdbdata.mdf' to '/var/opt/mssql/data/msdbdata.mdf'.
2023-11-14 15:09:31.75 Server      Setup step is copying system data file 'C:\templatedata\msdblog.ldf' to '/var/opt/mssql/data/msdblog.ldf'.
2023-11-14 15:09:31.75 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2023-11-14 15:09:31.76 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2023-11-14 15:09:31.76 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2023-11-14 15:09:31.77 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2023-11-14 15:09:31.80 Server      Microsoft SQL Server 2022 (RTM-CU9) (KB5030731) - 16.0.4085.2 (X64) 
trackingSep 27 2023 12:05:43           | 
trackingCopyright (C) 2022 Microsoft Corporation
trackingDeveloper Edition (64-bit) on Linux (Ubuntu 20.04.6 LTS) <X64>
2023-11-14 15:09:31.80 Server      UTC adjustment: 0:00
2023-11-14 15:09:31.80 Server      (c) Microsoft Corporation.
2023-11-14 15:09:31.80 Server      All rights reserved.
2023-11-14 15:09:31.80 Server      Server process ID is 504.
2023-11-14 15:09:31.80 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2023-11-14 15:09:31.80 Server      Registry startup parameters: 
tracking -d /var/opt/mssql/data/master.mdf
tracking -l /var/opt/mssql/data/mastlog.ldf
tracking -e /var/opt/mssql/log/errorlog| 
2023-11-14 15:09:31.81 Server      SQL Server detected 1 sockets with 12 cores per socket and 12 logical processors per socket, 12 total logical processors; using 12 logical processors based on SQL Server licensing. This is an informational message; no user action is required [...]

2023-11-14 16:49 UTC, FedeC87p commented
Ok, from what I see in the logs however it is only one error for each service (it is the DB check that tries to verify if the database is ready, therefore it is correct that there is an error), the checkDb will ensure that as long as the Database is not ready will not start the service.

Unlike before you should no longer have any services shutting down.


You can see the warning from the logs:
[15:09:39.448  WRN][]: Waiting for database  TrackingChain.AggregatorPoolWorker.WaitingDBHostedService 

As soon as the databases are ready the messages should disappear. I preferred to continue logging these types of errors rather than hiding them even though the DB was being checked

2023-11-14 23:24 UTC, takahser commented
@FedeC87p good call, let me have a look again tomorrow! I'll be back with feedback soon.

2023-11-15 21:00 UTC, takahser approved these changes
@FedeC87p you were right, the race conditions have been taken care of with your fix. I'm accepting this, you can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tracking_chain_4_takahser.md).

2023-11-15 21:04 UTC, merged

2023-11-29 11:44 UTC, RouvenP commented
hi @FedeC87p apologies for the delay in payment. We will settle the invoice before the end of the week and let you know as soon as done.

2023-11-29 11:45 UTC, FedeC87p commented
No problem, thanks for the update

2023-12-01 15:21 UTC, RouvenP commented
hi @FedeC87p we just paid the invoice. Thanks for your patience

2023-12-01 15:55 UTC, FedeC87p commented
Thank you