Patch 1
w3f/Grant-Milestone-Delivery pull request #1044
Opened 2023-10-31 23:54 UTC by leonardocustodio

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2004

2023-11-01 20:18 UTC, keeganquigley commented
Thanks for the delivery @leonardocustodio someone will look at it in the next few days.

2023-11-10 09:15 UTC, semuelle commented on deliveries/polkadart-milestone_3.md
> +https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_metadata
```suggestion
- https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart
- https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_cli
- https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_keyring
- https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart_scale_codec
- https://github.com/leonardocustodio/polkadart/tree/main/packages/ss58
- https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_bip39
- https://github.com/leonardocustodio/polkadart/tree/main/packages/substrate_metadata
```

2023-11-10 11:52 UTC, semuelle requested changes
Thanks for the delivery, @leonardocustodio. Everything looks pretty good, I'm just missing a link to deliverable 0e.

2023-11-10 11:59 UTC, leonardocustodio commented
Hello @semuelle , 
I have put the `demo` in gitignore (https://github.com/leonardocustodio/polkadart/blob/9b7ec8ef2e48b5d629a49c0f4276e4904b30f69e/.gitignore#L28) while I was working (because things were constantly changing) and forgot to take it out. I will do that as soon as I'm back, should be up by the end of the day, I will let you know, thank you for finding out.

2023-11-10 13:25 UTC, leonardocustodio commented
Here, I've added the `examples` folder to the repository: https://github.com/leonardocustodio/polkadart/tree/main/examples

2023-11-13 09:53 UTC, semuelle approved these changes
Thanks for the update, @leonardocustodio. Your milestone is hereby accepted. Congrats! You can see my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadart_3_semuelle.md). 

Looking forward to the next milestone.

2023-11-13 11:33 UTC, leonardocustodio commented
Thanks @semuelle :rocket:

2023-11-16 13:19 UTC, meldien commented
Hi @leonardocustodio 
Could you please add your full address on the invoice and send it again by the forms?
Many thanks in advance
Best wishes,
Melanie

2023-11-16 13:28 UTC, leonardocustodio commented
Hello @meldien , sorry missed that. I've submitted a new form with the updated invoice.
Thank you,
Leonardo

2023-11-27 20:42 UTC, leonardocustodio commented
@semuelle just making sure, should we merge this one?

2023-11-28 08:08 UTC, semuelle commented
> @semuelle just making sure, should we merge this one?

Thanks @leonardocustodio, totally missed that!

2023-11-28 08:09 UTC, merged

2023-11-28 13:24 UTC, leonardocustodio commented
@RouvenP thank you, appreciate it :)