Delivery of PoC Polkadot Conformance Tests
w3f/Grant-Milestone-Delivery pull request #1088
Opened 2023-12-22 20:48 UTC by ainhoa-a

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1956

2024-01-09 13:14 UTC, semuelle requested changes
@ainhoa-a, in the article, could you change "W3F foundation" to either "W3F" or, better yet, "Web3 Foundation"?

Regarding the rest of the deliverables, I hope to have some more feedback in a few days.

2024-01-23 08:47 UTC, ainhoa-a commented
Hi @semuelle sorry for the late reply, I was OOO. The article has now been modified.

2024-01-25 09:42 UTC, bhargavbh commented
My evaluation can be found here https://github.com/w3f/Grant-Milestone-Delivery/pull/1118

2024-01-26 20:20 UTC, keeganquigley commented
Thanks @ainhoa-a your milestone was accepted, and here is the merged [eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zondax_conformance_tests_1_bhargavbh.md). Thanks to @bhargavbh for the thorough evaluation, happy to pass it.

2024-01-26 20:20 UTC, merged