WeTEE Network Milestone 1  Delivery
w3f/Grant-Milestone-Delivery pull request #1095
Opened 2023-12-27 11:45 UTC by BurnWW

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2065

2024-01-08 07:32 UTC, takahser requested changes
@BurnWW unfortunately the build doesn't pass. Any idea why?

<details>
  <summary>Output</summary>

  ```zsh
  % cargo test -- --nocapture

  info: syncing channel updates for 'nightly-2023-08-22-aarch64-apple-darwin'
  info: latest update on 2023-08-22, rust version 1.74.0-nightly (ef85656a1 2023-08-21)
  info: downloading component 'cargo'
  info: downloading component 'clippy'
  info: retrying download for 'https://static.rust-lang.org/dist/2023-08-22/clippy-nightly-aarch64-apple-darwin.tar.xz'
  info: downloading component 'rust-docs'
  info: downloading component 'rust-std'
  info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
  info: downloading component 'rustc'
  info: downloading component 'rustfmt'
  info: installing component 'cargo'
  info: installing component 'clippy'
  info: installing component 'rust-docs'
  info: installing component 'rust-std'
  info: installing component 'rust-std' for 'wasm32-unknown-unknown'
  info: installing component 'rustc'
  info: installing component 'rustfmt'
      Updating git repository `https://github.com/paritytech/polkadot-sdk.git`
  warning: spurious network error (3 tries remaining): http parser error: stream ended at an unexpected time; class=Http (34)
  warning: spurious network error (2 tries remaining): http parser error: stream ended at an unexpected time; class=Http (34)
      Updating git repository `https://github.com/open-web3-stack/open-runtime-module-library.git`
      Updating crates.io index
      Updating git repository `https://github.com/w3f/ring-vrf`
      Updating git repository `https://github.com/w3f/fflonk`
      Updating git repository `https://github.com/w3f/ring-proof`
    Downloaded downcast v0.11.0
    Downloaded fdlimit v0.2.1
    Downloaded data-encoding-macro-internal v0.1.12
    Downloaded aead v0.3.2
    Downloaded lazycell v1.3.0
    Downloaded derive-syn-parse v0.1.5
    Downloaded macro_magic_core v0.4.2
    Downloaded base-x v0.2.11
    Downloaded block-modes v0.7.0
    Downloaded fixedbitset v0.4.2
    Downloaded base16ct v0.1.1
    Downloaded base64ct v1.6.0
    Downloaded displaydoc v0.2.4
    Downloaded directories v4.0.1
    Downloaded crypto-bigint v0.4.9
    Downloaded sec1 v0.3.0
    Downloaded crc-catalog v2.4.0
    Downloaded lz4 v1.24.0
    Downloaded ecdsa v0.16.9
    Downloaded aes v0.6.0
    Downloaded time-core v0.1.2
    Downloaded crypto-bigint v0.5.5
    Downloaded cexpr v0.6.0
    Downloaded dtoa v1.0.9
    Downloaded rpassword v7.3.1
    Downloaded base16ct v0.2.0
    Downloaded ark-ec v0.4.2
    Downloaded asn1-rs v0.3.1
    Downloaded der-parser v8.2.0
    Downloaded difflib v0.4.0
    Downloaded multibase v0.9.1
    Downloaded ark-ff-macros v0.4.2
    Downloaded ark-ff-asm v0.4.2
    Downloaded tracing-futures v0.2.5
    Downloaded ark-std v0.4.0
    Downloaded libp2p-connection-limits v0.1.0
    Downloaded peeking_take_while v0.1.2
    Downloaded slice-group-by v0.3.1
    Downloaded block-padding v0.2.1
    Downloaded sec1 v0.7.3
    Downloaded multistream-select v0.12.1
    Downloaded fs-err v2.11.0
    Downloaded libp2p-yamux v0.43.1
    Downloaded elliptic-curve v0.13.8
    Downloaded ed25519 v2.2.3
    Downloaded enum-as-inner v0.5.1
    Downloaded ark-ff v0.4.2
    Downloaded toml_edit v0.21.0
    Downloaded md-5 v0.10.6
    Downloaded exit-future v0.2.0
    Downloaded include_dir_macros v0.7.3
    Downloaded derive_builder_macro v0.11.2
    Downloaded dirs-sys-next v0.1.2
    Downloaded multimap v0.8.3
    Downloaded libp2p-dns v0.39.0
    Downloaded crc v3.0.1
    Downloaded spki v0.6.0
    Downloaded float-cmp v0.9.0
    Downloaded directories-next v2.0.0
    Downloaded clap v4.4.10
    Downloaded elliptic-curve v0.12.3
    Downloaded memmap2 v0.5.10
    Downloaded snap v1.1.0
    Downloaded quinn-proto v0.9.6
    Downloaded spki v0.7.3
    Downloaded mockall_derive v0.11.4
    Downloaded static_init v1.0.3
    Downloaded ed25519-dalek v2.1.0
    Downloaded ark-serialize-derive v0.4.2
    Downloaded tower-http v0.4.4
    Downloaded ark-serialize v0.4.2
    Downloaded cfg-expr v0.15.5
    Downloaded asn1-rs-derive v0.1.0
    Downloaded derive_builder v0.11.2
    Downloaded ark-poly v0.4.2
    Downloaded rtcp v0.7.2
    Downloaded const-oid v0.9.5
    Downloaded der v0.6.1
    Downloaded wide v0.7.13
    Downloaded arc-swap v1.6.0
    Downloaded libp2p-quic v0.7.0-alpha.3
    Downloaded pem-rfc7468 v0.6.0
    Downloaded webrtc-mdns v0.5.2
    Downloaded ccm v0.3.0
    Downloaded ecdsa v0.14.8
    Downloaded partial_sort v0.2.0
    Downloaded aes-soft v0.6.4
    Downloaded const-random-macro v0.1.16
    Downloaded nalgebra-macros v0.2.1
    Downloaded asn1-rs-impl v0.1.0
    Downloaded x25519-dalek v1.1.1
    Downloaded x25519-dalek v2.0.0
    Downloaded der v0.7.8
    Downloaded webrtc-ice v0.9.1
    Downloaded flate2 v1.0.28
    Downloaded bindgen v0.65.1
    Downloaded asn1-rs-derive v0.4.0
    Downloaded winnow v0.5.19
    Downloaded prost-derive v0.11.9
    Downloaded clap_builder v4.4.9
    Downloaded libp2p-core v0.39.2
    Downloaded webrtc v0.6.0
    Downloaded powerfmt v0.2.0
    Downloaded pem v1.1.1
    Downloaded blake3 v1.5.0
    Downloaded libp2p-ping v0.42.0
    Downloaded predicates v2.1.5
    Downloaded p256 v0.11.1
    Downloaded ark-bls12-381 v0.4.0
    Downloaded bzip2-sys v0.1.11+1.0.8
    Downloaded multiaddr v0.17.1
    Downloaded prost-types v0.11.9
    Downloaded bstr v1.8.0
    Downloaded data-encoding-macro v0.1.14
    Downloaded prost v0.11.9
    Downloaded pin-project-lite v0.1.12
    Downloaded wasm-opt v0.114.2
    Downloaded zstd-sys v2.0.9+zstd.1.5.5
    Downloaded rw-stream-sink v0.3.0
    Downloaded cranelift-bforest v0.95.1
    Downloaded quick-protobuf-codec v0.1.0
    Downloaded pest_generator v2.7.5
    Downloaded cranelift-native v0.95.1
    Downloaded cranelift-isle v0.95.1
    Downloaded cid v0.9.0
    Downloaded prometheus-client-derive-encode v0.4.2
    Downloaded asynchronous-codec v0.6.2
    Downloaded rand_pcg v0.3.1
    Downloaded der-parser v7.0.0
    Downloaded ark-ed-on-bls12-381-bandersnatch v0.4.0
    Downloaded void v1.0.2
    Downloaded docify_macros v0.2.7
    Downloaded semver v0.6.0
    Downloaded ark-scale v0.0.10
    Downloaded ark-scale v0.0.11
    Downloaded expander v2.0.0
    Downloaded quicksink v0.1.2
    Downloaded blake2s_simd v1.0.2
    Downloaded docify v0.2.7
    Downloaded wasm-instrument v0.3.0
    Downloaded waitgroup v0.1.2
    Downloaded cranelift-frontend v0.95.1
    Downloaded derive_builder_core v0.11.2
    Downloaded webpki v0.21.4
    Downloaded ip_network v0.4.1
    Downloaded toml v0.8.8
    Downloaded aquamarine v0.3.2
    Downloaded rawpointer v0.2.1
    Downloaded glob v0.3.1
    Downloaded sdp v0.5.3
    Downloaded handlebars v4.5.0
    Downloaded pest_derive v2.7.5
    Downloaded libp2p-tcp v0.39.0
    Downloaded http-range-header v0.3.1
    Downloaded rcgen v0.9.3
    Downloaded thousands v0.2.0
    Downloaded tt-call v1.0.9
    Downloaded rocksdb v0.21.0
    Downloaded clang-sys v1.6.1
    Downloaded pest_meta v2.7.5
    Downloaded quick-protobuf v0.8.1
    Downloaded webrtc-media v0.5.1
    Downloaded libp2p-webrtc v0.4.0-alpha.4
    Downloaded webrtc-srtp v0.9.1
    Downloaded time-macros v0.2.15
    Downloaded sct v0.6.1
    Downloaded globset v0.4.14
    Downloaded zstd-safe v6.0.6
    Downloaded linked_hash_set v0.1.4
    Downloaded libp2p-metrics v0.12.0
    Downloaded wasm-timer v0.2.5
    Downloaded rtp v0.6.8
    Downloaded fragile v2.0.0
    Downloaded proc-macro-warning v0.4.2
    Downloaded termtree v0.4.1
    Downloaded group v0.13.0
    Downloaded webrtc-sctp v0.7.0
    Downloaded simba v0.8.1
    Downloaded libp2p-noise v0.42.2
    Downloaded comfy-table v7.1.0
    Downloaded strum v0.25.0
    Downloaded prost-build v0.11.9
    Downloaded if-watch v3.2.0
    Downloaded filetime v0.2.22
    Downloaded trust-dns-proto v0.22.0
    Downloaded libloading v0.7.4
    Downloaded yasna v0.5.2
    Downloaded libp2p-request-r [...]

2024-01-08 10:31 UTC, BurnWW commented
Thank you @takahser, great to connect again. 
We apologize sincerely. This issue might be caused by the lack of necessary components during the initialization of the compilation environment. We have already fixed the links related to preparing the compilation environment in the Milestone 1 Test Guide.
Based on the log you provided:
> info: syncing channel updates for 'nightly-2023-08-22-aarch64-apple-darwin'
> Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.


Our preliminary assessment indicates that this problem is due to the absence of protoc in the macOS environment.

The fix is as follows:
Install `protoc` using `brew`:
```bash
## install protoc
$ brew install protobuf

## Validate protoc
$ protoc --version 
libprotoc 25.1
```

After successful installation, please perform the compilation operation again.

2024-01-09 09:35 UTC, takahser commented
@BurnWW thanks, that helped. I've made good progress, all the dependency installations, builds and tests can be run without any issues now. I've also added a [PR](https://github.com/paraspell/xcm-router/pull/7) that contains some fixes on your README. I'm currently smoke-testing the playground and writing up the evaluation, I'll be back soon with more feedback.

2024-01-09 09:59 UTC, takahser commented
@BurnWW thanks, that helped. I'm going to continue the evaluation, I'll be back with more feedback soon.

2024-01-12 05:16 UTC, takahser requested changes
@BurnWW I had issues when building the docker image - do you have an idea what could be the cause? I've added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/we-tee_1_takahser.md). LMK if you have any questions.

2024-01-12 13:15 UTC, BurnWW commented
Thank you @takahser, I have already fully understood the problem.
This error occurred because of the inability to connect to https://static.rust-lang.org. I have rebuilt the image and no longer temporarily download the build toolchain from https://static.rust-lang.org; instead, I am directly using a pre-configured build toolchain. I have updated this change in the DockerFile.

Based on the log you provided:
> 1363.8 Caused by:
1363.8     could not download file from 'https://static.rust-lang.org/dist/2023-08-22/cargo-nightly-x86_64-unknown-linux-gnu.tar.xz' to '/usr/local/rustup/downloads/49f5c4d796fe15d1578d71d39e1b12b2db5b258a94ddae29a44a226942f44919.partial'

Since the error is caused by network issues, subsequent compilations may still require downloading code from github.com and crates.io. If there are any network problems encountered, consider using the following methods to resolve them.
```
# Normal Compile Command
docker build  -f ./pos_build.Dockerfile -t wetee/wetee-node:dev .

# Using HTTP Proxy for Network Compilation
docker build --build-arg HTTPS_PROXY=http://<proxy_server_ip>:<port>  -f ./pos_build.Dockerfile -t wetee/wetee-node:dev .
```

2024-01-24 16:55 UTC, takahser requested changes
@BurnWW thanks for the update and sorry for the delay. The docker issue is resolved, however, for some reason I'm not able to access the node from the polkadot.js UI. Do you have any idea what could be the issue here?
I've also updated the evaluation [accordingly](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/we-tee_1_takahser.md). In case you can't reproduce the issue we can also have a [video call](https://calendar.app.google/FUDy24VjBW5HAF3w9) to speed things up.

2024-01-25 02:48 UTC, BurnWW commented
Thank you @takahser, I have already fully understood the problem.
Last update included a new docker run command, which I forgot to annotate in the reply; here is the complete run command.

```
docker run -p 9944:9944 wetee/wetee-node:dev
```

2024-01-29 09:08 UTC, takahser requested changes
(see message in Element channel)

2024-02-06 14:42 UTC, takahser approved these changes
@BurnWW thanks for your efforts and flexibility during this evaluation. I've accepted it, you can find the evaluation report [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/we-tee_1_takahser.md).

2024-02-06 14:42 UTC, merged

2024-02-16 17:33 UTC, RouvenP commented
hi @BurnWW we sent the payment today