ISO-8583 PoC Milestone 2
w3f/Grant-Milestone-Delivery pull request #1159
Opened 2024-03-22 16:39 UTC by dastansam

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [ ] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

2024-04-04 19:49 UTC, keeganquigley requested changes
Hi @dastansam working on your eval now. In the meantime, we will need to have you submit an amendment to take out the `zombienet` deliverable from the original contract since was originally agreed upon. This will require 3 approvals from the committee but should happen rather quickly. Perhaps you can also add an explanation about the PCIDSS Oracle Gateway.

Thanks! Let me know once it is submitted.

2024-04-04 19:54 UTC, keeganquigley commented
Additionally, an article was also included in the original application, but is not present in the milestone. Usually we ask teams to write at least a short blog article for this.

2024-04-05 16:26 UTC, keeganquigley commented
Thanks @dastansam there is also currently one test [failing](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/iso_8583_PoC_2_keeganquigley.md) if you can look into it. Thanks!

2024-04-05 20:11 UTC, keeganquigley commented
Thanks for the quick fix @dastansam can you confirm, is the [Demo merchant application](https://github.com/subclone/payment-processor/blob/main/interface/README.md) still the same from M1 or have there been changes? Should I just be completing the two main demos for this eval?

2024-04-05 20:24 UTC, keeganquigley commented
ah I see ok thanks for explaining the difference between these.

2024-04-05 22:22 UTC, keeganquigley requested changes
Moving on, `docker-compose up` works to start the `payment-processor`, but it seems to cause the iso8583 chain to panic for some reason:

```rust
2024-04-05 22:11:09.032  INFO tokio-runtime-worker substrate: ✨ Imported #260 (0x12eb…52f3)
2024-04-05 22:11:09.032 DEBUG tokio-runtime-worker offchain-worker: Spawning offchain workers at 0x12ebeeaaf1c0461956ccdc3bb65b4b1cd328754c096b5ada299000133e6a52f3
2024-04-05 22:11:09.033 DEBUG      offchain-worker offchain-worker: Running offchain workers at 0x12ebeeaaf1c0461956ccdc3bb65b4b1cd328754c096b5ada299000133e6a52f3
2024-04-05 22:11:09.060 ERROR      offchain-worker offchain-worker::http: Requested started id=430 method=POST uri=http://host.docker.internal:3001/balances
2024-04-05 22:11:09.065 DEBUG      offchain-worker offchain-worker::http: Added header to request id=430 name=Content-Type value=application/json
2024-04-05 22:11:09.065 DEBUG      offchain-worker offchain-worker::http: Added header to request id=430 name=accept value=*/*
2024-04-05 22:11:09.066 DEBUG      offchain-worker offchain-worker::http: Added new body chunk id=430
2024-04-05 22:11:09.070 DEBUG      offchain-worker offchain-worker::http: Added chunk to body id=430 res=Ok(())
2024-04-05 22:11:09.071 DEBUG      offchain-worker offchain-worker::http: Finished writing body id=430

====================

Version: 0.0.1-3c27d5df4f1

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:649:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
   4: rust_begin_unwind
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   5: core::panicking::panic_fmt
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   6: <rustls::builder::ConfigBuilder<rustls::client::client_conn::ClientConfig,rustls::builder::WantsVerifier> as hyper_rustls::config::ConfigBuilderExt>::with_native_roots
   7: hyper_rustls::connector::builder::ConnectorBuilder<hyper_rustls::connector::builder::WantsTlsConfig>::with_native_roots
   8: core::ops::function::FnOnce::call_once
   9: once_cell::imp::OnceCell<T>::initialize::{{closure}}
  10: once_cell::imp::initialize_or_wait
  11: once_cell::imp::OnceCell<T>::initialize
  12: <sc_offchain::api::http::HttpWorker as core::future::future::Future>::poll
  13: sc_offchain::OffchainWorkers<RA,Block,Storage>::on_block_imported::{{closure}}
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run
  20: tokio::runtime::context::runtime::enter_runtime
  21: tokio::runtime::scheduler::multi_thread::worker::run
  22: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::raw::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone


Thread 'tokio-runtime-worker' panicked at 'no CA certificates found', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.24.1/src/config.rs:48

This is a bug. Please report it at:
```
Something about the CA certificates, do you know if it should run successfully on Mac? Thanks!

2024-04-05 22:31 UTC, keeganquigley commented
FYI @dastansam I was using the first option, ready to use Docker image so perhaps it has to do with that. Will try compiling with cargo.

2024-04-08 21:06 UTC, keeganquigley commented
Awesome thanks @dastansam sure will try now.

2024-04-09 01:46 UTC, keeganquigley commented
Hey @dastansam maybe its best if we could jump on a call to go over proper steps, because I am still running into some issues. I just DM'ed you.

2024-04-09 16:41 UTC, keeganquigley commented
Thanks again @dastansam for the call, was able to get everything working, please see [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/iso_8583_PoC_2_keeganquigley.md). I'm happy to pass the milestone, congrats on the completion of the grant!

2024-04-09 16:42 UTC, merged

2024-04-12 12:59 UTC, RouvenP commented
hi @dastansam we just sent the payment