MeProtocol Milestone 2 Delivery
w3f/Grant-Milestone-Delivery pull request #1182
Opened 2024-05-21 10:52 UTC by AgentPoles

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1340 
Link to Milestone-1-Delivery pull request: https://github.com/w3f/Grant-Milestone-Delivery/pull/1065

2024-05-27 10:41 UTC, semuelle requested changes
Also, the code isn't compiling. `cargo test` (1.78.0) results in the following output (notice also the many warnings):

```sh
> cargo test
   Compiling global v0.1.0 (/me-protocol/rusty-protocol-v0.1/contracts)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> contracts/global.rs:2:1
  |
2 | #![feature(min_specialization)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `psp22::PSP22Impl`
 --> contracts/controllers/deployables/reward.rs:5:8
  |
5 |     }, psp22::PSP22Impl},
  |        ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `psp22::*`, `psp34::extensions::enumerable`
 --> contracts/controllers/deployables/a_pool.rs:2:46
  |
2 |     contracts::{traits::{ access_control::*, psp22::*, psp34::*, pausable::* }, psp34::extensions::enumerable},
  |                                              ^^^^^^^^                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `psp22::*`
 --> contracts/controllers/deployables/treasury.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::* },
  |                                             ^^^^^^^^

warning: unused import: `prelude::vec::Vec`
 --> contracts/controllers/deployables/treasury.rs:7:12
  |
7 | use ink::{ prelude::vec::Vec };
  |            ^^^^^^^^^^^^^^^^^

warning: unused import: `data::a_pool::*`
 --> contracts/controllers/deployables/treasury.rs:9:58
  |
9 | use crate::providers::{ common::{ errors::*, types::* }, data::a_pool::* };
  |                                                          ^^^^^^^^^^^^^^^

warning: unused import: `psp22::*`
 --> contracts/controllers/deployables/bounty.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::* },
  |                                             ^^^^^^^^

warning: unused import: `prelude::vec::Vec`
 --> contracts/controllers/deployables/bounty.rs:6:12
  |
6 | use ink::{ prelude::vec::Vec };
  |            ^^^^^^^^^^^^^^^^^

warning: unused import: `data::a_pool::*`
 --> contracts/controllers/deployables/bounty.rs:8:44
  |
8 | use crate::providers::{ common::errors::*, data::a_pool::* };
  |                                            ^^^^^^^^^^^^^^^

warning: unused import: `psp22::*`
 --> contracts/controllers/deployables/payment.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::* },
  |                                             ^^^^^^^^

warning: unused import: `openbrush::traits::String`
 --> contracts/controllers/deployables/payment.rs:5:5
  |
5 | use openbrush::traits::String;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `prelude::vec::Vec`
 --> contracts/controllers/deployables/payment.rs:7:12
  |
7 | use ink::{ prelude::vec::Vec };
  |            ^^^^^^^^^^^^^^^^^

warning: unused imports: `data::a_pool::*`, `types::*`
 --> contracts/controllers/deployables/payment.rs:9:46
  |
9 | use crate::providers::{ common::{ errors::*, types::* }, data::a_pool::* };
  |                                              ^^^^^^^^    ^^^^^^^^^^^^^^^

warning: unused imports: `Balance`, `psp22::*`
 --> contracts/controllers/deployables/pool_initiator.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::* },
  |                                             ^^^^^^^^
3 |     traits::{ AccountId, Balance },
  |                          ^^^^^^^

warning: unused import: `openbrush::traits::String`
 --> contracts/controllers/deployables/pool_initiator.rs:5:5
  |
5 | use openbrush::traits::String;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `errors::*`
  --> contracts/controllers/deployables/pool_initiator.rs:10:35
   |
10 | use crate::providers::{ common::{ errors::*, types::* }, data::a_pool::* };
   |                                   ^^^^^^^^^

warning: unused import: `psp22::*`
 --> contracts/controllers/deployables/reward_initiator.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::* },
  |                                             ^^^^^^^^

warning: unused import: `data::a_pool::*`
  --> contracts/controllers/deployables/reward_initiator.rs:10:58
   |
10 | use crate::providers::{ common::{ errors::*, types::* }, data::a_pool::* };
   |                                                          ^^^^^^^^^^^^^^^

warning: unused imports: `pausable::*`, `psp22::*`
 --> contracts/controllers/services/brands.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::*, psp34::*, pausable::* },
  |                                             ^^^^^^^^            ^^^^^^^^^^^

warning: unused import: `prelude::vec::Vec`
 --> contracts/controllers/services/brands.rs:8:12
  |
8 | use ink::{ prelude::vec::Vec };
  |            ^^^^^^^^^^^^^^^^^

warning: unused imports: `String`, `access_control::*`, `pausable::*`, `psp22::*`, `psp34::*`
 --> contracts/controllers/services/customers.rs:2:26
  |
2 |     contracts::traits::{ access_control::*, psp22::*, psp34::*, pausable::* },
  |                          ^^^^^^^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^
3 |     traits::{ AccountId, Balance, String },
  |                                   ^^^^^^

warning: unused imports: `a_pool::*`, `a_reward::*`, `brand::*`
 --> contracts/controllers/services/customers.rs:6:52
  |
6 | use crate::providers::{ common::errors::*, data::{ a_reward::*, brand::*, a_pool::* } };
  |                                                    ^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^^

warning: unused imports: `Balance`, `pausable::*`, `psp22::*`, `psp34::*`
 --> contracts/controllers/services/admin.rs:2:45
  |
2 |     contracts::traits::{ access_control::*, psp22::*, psp34::*, pausable::* },
  |                                             ^^^^^^^^  ^^^^^^^^  ^^^^^^^^^^^
3 |     traits::{ AccountId, Balance, String },
  |                          ^^^^^^^

warning: unused imports: `a_pool::*`, `a_reward::*`, `brand::*`, `treasury::*`
 --> contracts/controllers/services/admin.rs:6:64
  |
6 | ...rrors::*, types::*}, data::{ a_reward::*, brand::*, a_pool::*, protocol::*, treasury::* } };
  |                                 ^^^^^^^^^^^  ^^^^^^^^  ^^^^^^^^^               ^^^^^^^^^^^

warning: type `BRAND_ID_TYPE` should have an upper camel case name
 --> contracts/providers/common/types.rs:1:10
  |
1 | pub type BRAND_ID_TYPE = [u8; 10];
  |          ^^^^^^^^^^^^^ help: convert the identifier to upper camel case: `BrandIdType`
  |
  = note: `#[warn(non_camel_case_types)]` on by default

warning: unused import: `storage::traits::StorageLayout`
 --> contracts/providers/common/context.rs:3:12
  |
3 | use ink::{ storage::traits::StorageLayout };
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::providers::common::database::*`
 --> contracts/providers/common/context.rs:4:5
  |
4 | use crate::providers::common::database::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `Decode`
 --> contracts/providers/common/roleguard.rs:6:13
  |
6 | use scale::{Decode, Encode};
  |             ^^^^^^

warning: unused imports: `env::hash::Keccak256`, `storage::Mapping`
 --> contracts/providers/common/roleguard.rs:7:11
  |
7 | use ink::{env::hash::Keccak256, prelude::{collections::BTreeMap, vec::Vec}, storage::Mapping};
  |           ^^^^^^^^^^^^^^^^^^^^                                              ^^^^^^^^^^^^^^^^

warning: unused import: `crate::controllers::services::admin`
  --> contracts/providers/common/roleguard.rs:10:5
   |
10 | use crate::controllers::services::admin;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::providers::common::database::*`
 --> contracts/providers/data/a_pool.rs:4:5
  |
4 | use crate::providers::common::database::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `AccountId`
 --> contracts/providers/data/a_position.rs:2:46
  |
2 | use openbrush::{ storage::Mapping, traits::{ AccountId, Balance}, contracts::traits::psp34::Id };
  |                                              ^^^^^^^^^

warnin [...]

2024-05-29 02:06 UTC, dsm-w3f commented
Hi, we'll evaluate this milestone.

2024-05-29 21:12 UTC, AgentPoles commented
Hi @semuelle sorry I was out of office last week, the updates have now been made appropriately! Please check again and let me know. Thank you very much!

2024-05-30 15:24 UTC, AgentPoles commented
Hi @semuelle thanks a lot for the feedback: 

4. The cargo tests are simply unit tests, the major end to end tests are dockerize and can be run by following the instructions [here](https://github.com/Me-Protocol/rusty-protocol-v0.1/blob/milestone-2/testing_guide.md#running-the-docker-file-for-the-e2e-test)

3. for 2: Some functions are definitely missing on this branch, will review it immediately. But just to add, we had to move away from the original lens proposition because of the halt in the work on the diamond standard by openBrush, which is the major framework for our development. This oracle only exposes the secretary functionalities

2. `0e`: alright, this is duly noted will adjust appropriately, thanks lot!

1. `0b`: the actual screens for the interaction would be ready at the end of milestone 3, hence the full fledged tutorial from the UI.  But given this comment, we will make a video tutorial to showcase from the terminal how some of these interactions can be carried out, would that suffice?

Also just to add, we will make sure we expose a deployed version of the backend and also serve the frontend for the milestone 3.

2024-05-31 08:13 UTC, semuelle commented
Thanks for the quick reply, @AgentPoles. 

> * The cargo tests are simply unit tests, the major end to end tests are dockerize and can be run by following the instructions [here](https://github.com/Me-Protocol/rusty-protocol-v0.1/blob/milestone-2/testing_guide.md?rgh-link-date=2024-05-30T15%3A24%3A53Z#running-the-docker-file-for-the-e2e-test)

Sorry for that. Like I mentioned, I didn't get very far with the e2e tests, so I had another stab at it. However, I might be misunderstanding something, because if I start a contracts node and then run `docker run -p 9944:9944 my-rust-environment:v1`, all I get is

```sh
docker: Error response from daemon: driver failed programming external connectivity on endpoint crazy_diffie (da15b9f6a43d043e5af03c6c57874a282e78eb6ef5b252fb15bb069824da31a1): Error starting userland proxy: listen tcp4 0.0.0.0:9944: bind: address already in use.
ERRO[0000] error waiting for container: context canceled 
```

> * for 2: Some functions are definitely missing on this branch, will review it immediately. But just to add, we had to move away from the original lens proposition because of the halt in the work on the diamond standard by openBrush, which is the major framework for our development. This oracle only exposes the secretary functionalities

I'm not familiar with the lens proposition or secretary functionalities. If this code covers what was planned, can you add a sentence or two about it in the delivery file, explaining what changed? 

> * `0b`: the actual screens for the interaction would be ready at the end of milestone 3, hence the full fledged tutorial from the UI.  But given this comment, we will make a video tutorial to showcase from the terminal how some of these interactions can be carried out, would that suffice?

A tutorial doesn't have to include a UI, especially when it's not ready anyway. The tools are up to you. Some provide polkadot.js apps screenshots, some a list of bash commands, some video tutorials. Though I'd argue it's best if it's easy to follow and reproduce.

2024-06-06 10:02 UTC, semuelle commented
pinging @AgentPoles

2024-06-17 07:46 UTC, semuelle commented
again pinging @AgentPoles, and @Adebara123.

2024-06-19 07:22 UTC, AgentPoles commented
Hi @semuelle Sorry for the delays, we are updating shortly. 🙏

2024-06-25 10:25 UTC, AgentPoles commented
Hello @semuelle we have now completed all the updates from our end. For the Article do we need to forward to the email: [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) for review first, or we just proceed to attach here

2024-07-01 11:30 UTC, semuelle commented
> For the Article do we need to forward to the email: [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) for review first, or we just proceed to attach here

Hi @AgentPoles, sorry for the late reply. No need to involve grantsPR anymore if the article is linked in the delivery document.

I will review the changes asap.

2024-07-02 12:39 UTC, semuelle reviewed
> Sorry for that. Like I mentioned, I didn't get very far with the e2e tests, so I had another stab at it. However, I might be misunderstanding something, because if I start a contracts node and then run `docker run -p 9944:9944 my-rust-environment:v1`, all I get is
> 
> ```shell
> docker: Error response from daemon: driver failed programming external connectivity on endpoint crazy_diffie (da15b9f6a43d043e5af03c6c57874a282e78eb6ef5b252fb15bb069824da31a1): Error starting userland proxy: listen tcp4 0.0.0.0:9944: bind: address already in use.
> ERRO[0000] error waiting for container: context canceled 
> ```

Thanks for the updates, @AgentPoles. Do you have any input for the issue with the tests mentioned above?

2024-07-02 14:31 UTC, AgentPoles commented
Yes we changed the port to 9945 as we figured out the original port 9944 could already be in use on your device. We also showed the full process in the first part of the tutorial video.

2024-07-02 17:46 UTC, semuelle commented
> Yes we changed the port to 9945 as we figured out the original port 9944 could already be in use on your device.

Well, the instructions said to start a contracts node, so I assume that's occupying 9944.

2024-07-06 04:58 UTC, AgentPoles commented
Hello @semuelle , are you good now? yes it's occupying 9944 but you can also change the port. Just see the video tutorial for the guidelines

2024-07-08 10:37 UTC, semuelle reviewed
@AgentPoles, I followed the video instructions, but when I run the docker tests, I'm only getting `Abnormal Closure`s, no matter what port I use. Any suggestions?

```sh
> docker run -p 9945:9945 my-rust-environment:v1

  Bounty Test
    recordDepositedBountyRewards
2024-07-08 09:35:32          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:35          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:37          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:40          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:42          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:45          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
2024-07-08 09:35:47          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure
...
```

2024-07-11 10:26 UTC, semuelle commented
Hi @AgentPoles, yes, we can arrange a call. However, I suspect that this is simply a version mismatch somewhere. I just upgraded my nightly toolchain, and now I'm getting the following error. Perhaps you could add your contracts-node, rust and toolchain versions in the test instructions so I can replicate it.

```sh
> npx mocha --require @babel/register --require ts-node/register --recursive ./tests --extension \".ts\" --exit --timeout 20000

  Bounty Test
    recordDepositedBountyRewards
2024-07-11 12:24:02        API/INIT: substrate-contracts-node/100: Not decorating runtime apis without matching versions: Core/5 (1/2/3/4 known)
2024-07-11 12:24:02        API/INIT: substrate-contracts-node/100: Not decorating unknown runtime apis: 0xfbc577b9d747efd6/1
balance of bounty 100
      ✔ Should successfully record bounty amount (932ms)
2024-07-11 12:24:02        API/INIT: substrate-contracts-node/100: Not decorating runtime apis without matching versions: Core/5 (1/2/3/4 known)
2024-07-11 12:24:02        API/INIT: substrate-contracts-node/100: Not decorating unknown runtime apis: 0xfbc577b9d747efd6/1
balance of bounty 0
      ✔ Should fail because your are trying to record an amount you didn't deposit (624ms)
    withdrawBountyRewards
2024-07-11 12:24:03        API/INIT: substrate-contracts-node/100: Not decorating runtime apis without matching versions: Core/5 (1/2/3/4 known)
2024-07-11 12:24:03        API/INIT: substrate-contracts-node/100: Not decorating unknown runtime apis: 0xfbc577b9d747efd6/1
```

2024-07-11 13:28 UTC, semuelle commented
> most of the packages are in the docker file

This last output is not using Docker. The Docker version is still giving `API-WS: disconnected from ws://host.docker.internal:9944: 1006:: Abnormal Closure`. And you are also working with the `milestone-2` branch, correct?
```

[Here](https://calendar.app.google/xxCih58No5U4Lgt9A) is a link to my calendar.

2024-07-12 09:15 UTC, AgentPoles commented
Hello @semuelle  I book a call with you for now, but can't see a meeting link my email is paul@myai.life

2024-07-12 10:06 UTC, AgentPoles commented
thanks for the call!

2024-07-12 10:47 UTC, semuelle commented
@AgentPoles, I can confirm now that the warning messages on the tests do not appear with contracts-node version 0.35.0. It would be great if you could look into resolving the messages using 0.41.0. Other than that, I will try to finish the rest of the evaluation later today.

2024-07-12 11:12 UTC, semuelle approved these changes
Hi again, @AgentPoles. I just checked off the rest of the deliverables. I'm happy to report that your milestone is accepted. Congratulations! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/MeProtocol_2_semuelle.md).

As mentioned above, it'd be great if you could look into the warnings in the tests. Other than that, nice work!

Since the next will be your last milestone, it'd be great if you could then provide a guide how to test the whole project manually, e.g. with a step-by-step how to create a rewards program, how to earn and how to redeem points through the app.

2024-07-12 11:12 UTC, merged

2024-07-12 11:32 UTC, AgentPoles commented
Alright @semuelle thanks a lot! you are the best!

2024-07-15 10:20 UTC, semuelle commented
@AgentPoles, the payment information on the invoice doesn't match the ones you sent to us via email. If they have changed, please send another email with the new payment details from the same email address you used for the first email. Thanks!

2024-07-15 11:34 UTC, rnwesley commented
@semuelle What email are you referring to? I used the form to submit the invoice.

2024-07-15 12:20 UTC, semuelle commented
Thanks!