Polkadot Runtime Releaser Milestone 1
w3f/Grant-Milestone-Delivery pull request #1236
Opened 2024-12-28 08:30 UTC by AurevoirXavier

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2373

2024-12-28 08:36 UTC, AurevoirXavier commented
It looks like that I formatted the old deliveries lead the actions failed.

2024-12-30 14:25 UTC, semuelle requested changes
Thanks for the delivery, @AurevoirXavier, but it looks like you are submitting changes to multiple unrelated files with your PR. It'd be great if your PR only included the delivery document you want to submit.

2025-01-03 13:35 UTC, PieWol commented
Hey @AurevoirXavier ,
I noticed that the default section for the link to your application document is not adjusted correctly. Please delete the default wording and link to your application file :)
Thanks!

2025-01-03 19:01 UTC, AurevoirXavier commented
> Hey @AurevoirXavier , I noticed that the default section for the link to your application document is not adjusted correctly. Please delete the default wording and link to your application file :) Thanks!

I was still wondering why the CI failed. Stupid mistake. 😅

2025-01-09 11:07 UTC, aurexav commented
Hi there, when can we start to evaluate this?🙏

2025-01-13 13:04 UTC, PieWol commented
Hey @aurexav ,
sorry for the delay. The evaluation will start this week. Hope that works for you.

2025-01-17 15:41 UTC, PieWol commented
Hey @aurexav ,
thanks for your delivery. I'm happy to accept it. See [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/runtime_releaser_1_piewol.md) for the evaluation. I hope this makes CI and deployment more convenient for many teams :)
🎉

2025-01-17 15:41 UTC, merged

2025-01-17 15:52 UTC, aurexav commented
> Hey @aurexav ,
> 
> thanks for your delivery. I'm happy to accept it. See [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/runtime_releaser_1_piewol.md) for the evaluation. I hope this makes CI and deployment more convenient for many teams :)
> 
> 🎉 

Thank you!

And I think I have already submitted the invoice form?

2025-01-29 08:23 UTC, aurexav commented
Hi there, it’s been two weeks since I submitted the invoice. I haven’t received the fund yet. Could you please check if there’s anything missing?

2025-01-29 09:50 UTC, semuelle commented
Hi @aurexav. The payment should go out on Friday.

2025-01-31 08:45 UTC, RouvenP commented
hi @aurexav I noticed you indicate Asset Hub as target chain for the DOT payment. Since the DOTs are locked you wouldn't be able to stake them or to teleport them - should we send them on the relay chain instead?

2025-01-31 09:53 UTC, aurexav commented
> hi @aurexav I noticed you indicate Asset Hub as target chain for the DOT payment. Since the DOTs are locked you wouldn't be able to stake them or to teleport them - should we send them on the relay chain instead?

Thanks, please go Polkadot.

2025-02-03 07:37 UTC, RouvenP commented
we sent the payments on Friday @aurexav