Parachain Staking Milestone 2: UI Dashboard
w3f/Grant-Milestone-Delivery pull request #321
Opened 2021-12-08 16:51 UTC by 4meta5

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/389

2021-12-08 17:06 UTC, 4meta5 commented on deliveries/parachain_staking_2.md
> +* **PR Link:** https://github.com/w3f/Grants-Program/pull/389
```suggestion
* **Application Document:** https://github.com/w3f/Grants-Program/blob/master/applications/parachain-staking.md
```

2021-12-08 19:36 UTC, semuelle commented
Thank you for the delivery, Amar. We will look into it as soon as possible.

2021-12-10 14:19 UTC, Noc2 requested changes
Thanks again for the delivery. I quickly looked into it and everything seems to work. However, the UI only provides an overview of the current staking initiatives and doesn’t actually let you participate in the staking. Is this on-purpose? I know the deliveries were unspecific in the contract, but I would have expected that you can also stake via the UI.

2021-12-10 21:31 UTC, 4meta5 commented
> Doesn't actually let you participate in the staking. Is this on-purpose? I know the deliveries were unspecific in the contract, but I would have expected that you can also stake via the UI.

OK, we will add this functionality, but it will require another 2 weeks. I'll let you know as soon as it is done.

Our perspective was that the deliverable needed to display meaningful statistics to educate user staking through whatever custom UI is provided by the implementation. For moonbeam/moonriver, we prefer users use the staking dapp provided by PureStake (https://apps.moonbeam.network/moonriver).

2021-12-13 08:26 UTC, Noc2 commented
Thanks for the quick reply. I think it would be beneficial if you add it directly to the UI. Alternatively you could also link to your own staking dapp, to at least inform users about how they can participate.

2022-01-17 18:11 UTC, alxs commented
@4meta5 any updates?

2022-01-17 21:11 UTC, 4meta5 commented
@alxs We decided to add the `delegate` feature to the UI dashboard but it is currently in progress and will be done soon. Our best TS dev @joelamouche is working on it. He was busy with tasks for Moonbeam launch, but is back on this now.

2022-02-15 22:18 UTC, alxs commented
@4meta5 @joelamouche checking in again. Could you provide an ETA?

2022-02-16 12:36 UTC, crystalin commented
@alxs Sorry, @joelamouche is not working on this project anymore. 
Our team took over and I believe it is close to completion. Let me come back you today

2022-02-16 14:04 UTC, purestaketdb commented
I am onboarding @fxgamundi to the project this week, he'll need to get up to speed on the Polkadot.js libraries but is the developer on our own staking dapp. I'll have more clarity about timelines next week. Note, basic staking is working but the pallet was extended in December and those changes need to be rolled in.

2022-02-16 14:33 UTC, alxs commented
Thanks @crystalin @purestaketdb, sounds good. Please keep us posted.

2022-03-01 14:46 UTC, fxgamundi commented
Hi! Nice to meet everyone. I'm currently working on this and will be able to provide an update on the status and an ETA later in the week.

2022-03-09 14:47 UTC, fxgamundi commented
Hey! Progress is going well and we should have a it ready for review by the end of next week.

2022-03-09 15:13 UTC, Noc2 commented
That’s great to hear.

2022-03-24 04:52 UTC, fxgamundi commented
We're doing a final internal review before submitting the updated code. We'll follow with the PR later today

2022-03-24 13:41 UTC, Noc2 commented
Sounds good. It’s not super urgent. I’m currently sick (covid) and can not work much anyway ;-)

2022-03-25 02:14 UTC, fxgamundi commented
Sorry to hear that, get better!  In that case I will take some additional time to clean a couple of things.

2022-03-30 14:07 UTC, fxgamundi commented
Hi! The PR for the parachain staking page is up! https://github.com/polkadot-js/apps/pull/7275

2022-04-04 13:39 UTC, Noc2 approved these changes
Sorry for the late reply here. I’m happy to tell you that the milestone is a pass and thanks for all the extra effort you put into this. I will forward your invoice internally.

2022-04-04 13:39 UTC, merged

2022-04-04 14:01 UTC, meldien commented
Hi all, is it possible to update the invoice date?

2022-04-05 19:27 UTC, 4meta5 commented
@meldien the invoice was submitted via the google form from what I remember? would you like us to submit a new invoice via the google form? Feel free to send the old invoice to `stefan@purestake.com` and we can also figure this out over email

2022-04-06 08:43 UTC, meldien commented
@4meta5  @Noc2 yes that would be great if you can submit a new invoice during google form. because the date is from 2021 and the approval are done in 2022.

2022-04-11 08:05 UTC, meldien commented
@4meta5 any update?

2022-04-13 19:06 UTC, 4meta5 commented
@meldien we have assigned the task of sending the new invoice to someone else internally and will submit it soon @crystalin

2022-04-20 09:56 UTC, fededubbi commented
Hi all, any updates here?

Many thanks,
Federica

2022-04-20 20:18 UTC, 4meta5 commented
I submitted an updated invoice. Let me know if there are any problems with the submission.

2022-05-02 15:27 UTC, RouvenP commented
hi @4meta5 we transferred the payment today. Thanks!