Ruby protocol: milestone 2
w3f/Grant-Milestone-Delivery pull request #332
Opened 2021-12-31 02:47 UTC by rubyprotocol

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/Ruby-Protocol/Grant-Milestone-Delivery/blob/master/deliveries/ruby_milestone_2.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/311.

2022-01-03 10:40 UTC, Noc2 commented
Thanks for the delivery. We will look into it as soon as possible.

2022-01-05 02:52 UTC, rubyprotocol commented
> @rubyprotocol could you merge master into your branch? I think that should remove the first delivery from the added files and get the checks to pass.

I just delete the milestone 1 delivery, but the check doesn't seem to pass?

2022-01-13 02:52 UTC, lornacrevelingwgo23 commented
Hey @Noc2 @alxs @mmagician, this is a gentle reminder that we are still waiting for your comments on our milestone 2 delivery. Thx.

2022-01-13 08:12 UTC, mmagician commented
@lornacrevelingwgo23 thanks. I've already started looking into it, will give you some feedback by the end of the week.

2022-01-13 12:03 UTC, alxs commented on deliveries/ruby_milestone_2.md
> +* **PR Link:** https://github.com/w3f/Grants-Program/pull/311
This also needs to be updated.

```suggestion
* **Application Document:** https://github.com/w3f/Grants-Program/blob/master/applications/RubyProtocol.md
```

2022-01-14 07:03 UTC, rubyprotocol commented on deliveries/ruby_milestone_2.md
> +* **PR Link:** https://github.com/w3f/Grants-Program/pull/311
Sure, already update it.

2022-01-14 18:57 UTC, mmagician commented
@rubyprotocol Before we proceed any further, I've noticed that you have duplicated the entire ZeroPool repo **again** into your code. This was already pointed out in the previous evaluation, please see [here](https://github.com/w3f/Grant-Milestone-Delivery/commit/42aa431f8e8e917ac216579b90feb9d91951f050) I understand from your tutorial that now it is used to demonstrate the milestone deliverables, but your code should ideally be a library - right now it's really looking just like a "project delivery", where the node, the client **and** the UI is bundled into one. Please bear in mind that one of the objectives of the Grants Program is to enable other community members to easily import your code and re-use it for their own project.

I would suggest you refactor your code and instead either simply point to the correct repository, giving instructions on how to build and run it (you don't need to duplicate whatever instructions ZeroPool has), or if you have objections to the first method, you can include that as a submodule (while it doesn't really fit an idea of submodule, in my opinion that's still better than including the entirety of the source code). Please re-think your approach to making the client and UI into stand-alone applications with clear, pluggable APIs.

Thanks for understanding.

2022-01-15 01:04 UTC, lornacrevelingwgo23 commented
> @rubyprotocol Before we proceed any further, I've noticed that you have duplicated the entire ZeroPool repo **again** into your code. This was already pointed out in the previous evaluation, please see [here](https://github.com/w3f/Grant-Milestone-Delivery/commit/42aa431f8e8e917ac216579b90feb9d91951f050) I understand from your tutorial that now it is used to demonstrate the milestone deliverables, but your code should ideally be a library - right now it's really looking just like a "project delivery", where the node, the client **and** the UI is bundled into one. Please bear in mind that one of the objectives of the Grants Program is to enable other community members to easily import your code and re-use it for their own project.
> 
> I would suggest you refactor your code and instead either simply point to the correct repository, giving instructions on how to build and run it (you don't need to duplicate whatever instructions ZeroPool has), or if you have objections to the first method, you can include that as a submodule (while it doesn't really fit an idea of submodule, in my opinion that's still better than including the entirety of the source code). Please re-think your approach to making the client and UI into stand-alone applications with clear, pluggable APIs.
> 
> Thanks for understanding.

Sure, thanks for your comments. Will get it done soon.

2022-01-17 01:37 UTC, lornacrevelingwgo23 commented
> * milestone-delivery-template.md

Hey @mmagician, already refactor the code according to your instruction. Please check our [repo](https://github.com/rubyprotocol/Ruby_milestone2) for the update.

2022-01-17 01:39 UTC, lornacrevelingwgo23 commented
> @rubyprotocol Before we proceed any further, I've noticed that you have duplicated the entire ZeroPool repo **again** into your code. This was already pointed out in the previous evaluation, please see [here](https://github.com/w3f/Grant-Milestone-Delivery/commit/42aa431f8e8e917ac216579b90feb9d91951f050) I understand from your tutorial that now it is used to demonstrate the milestone deliverables, but your code should ideally be a library - right now it's really looking just like a "project delivery", where the node, the client **and** the UI is bundled into one. Please bear in mind that one of the objectives of the Grants Program is to enable other community members to easily import your code and re-use it for their own project.
> 
> I would suggest you refactor your code and instead either simply point to the correct repository, giving instructions on how to build and run it (you don't need to duplicate whatever instructions ZeroPool has), or if you have objections to the first method, you can include that as a submodule (while it doesn't really fit an idea of submodule, in my opinion that's still better than including the entirety of the source code). Please re-think your approach to making the client and UI into stand-alone applications with clear, pluggable APIs.
> 
> Thanks for understanding.

Hey @mmagician, already refactor the code according to your instruction. Please check our [repo](https://github.com/rubyprotocol/Ruby_milestone2) for the update.

2022-01-17 14:43 UTC, mmagician commented
Why are you [re-defining](https://github.com/rubyprotocol/Ruby_milestone2/blob/main/ruby-api/src/zk/types.rs) the types that you import from fawkes_crypto? This seems overly confusing, especially that sometimes you're re-importing these and you then have both crate-local type definition and original definitions from fawkes_crypto.

2022-01-18 02:18 UTC, lornacrevelingwgo23 commented
> Why are you [re-defining](https://github.com/rubyprotocol/Ruby_milestone2/blob/main/ruby-api/src/zk/types.rs) the types that you import from fawkes_crypto? This seems overly confusing, especially that sometimes you're re-importing these and you then have both crate-local type definition and original definitions from fawkes_crypto.

Thanks for your comments. This is actually an optimization of the original private_ml code for milestone 1 delivery. It aims to ensure the consistency of curves used by our functional encryption scheme and zero-knowledge proof scheme of zeropool so that the verification can always be successful.

2022-01-18 14:14 UTC, mmagician commented
Hmm okay, I think it's confusing but if you say it's a conscious design decision - that's fine.
Lastly, there are multiple formatting and clippy issues, this was already reported in Milestone 1 evaluation. Please address them all (clippy as well as cargo fmt). 

Also, it would be beneficial to see more elaborate tests: e.g. the inner product only takes an array of **1** elements, which is too trivial IMO to constitute a proper test.

2022-01-19 07:22 UTC, lornacrevelingwgo23 commented
> Reference in



> Hmm okay, I think it's confusing but if you say it's a conscious design decision - that's fine. Lastly, there are multiple formatting and clippy issues, this was already reported in Milestone 1 evaluation. Please address them all (clippy as well as cargo fmt).
> 
> Also, it would be beneficial to see more elaborate tests: e.g. the inner product only takes an array of **1** elements, which is too trivial IMO to constitute a proper test.

Thanks for your comments. Already fix the clippy and fmt issues. Please check the [repo](https://github.com/rubyprotocol/Ruby_milestone2) for update. Regarding tests, although our tutorial only gives an example of an array of two elements, our apps work fine with arrays of multiple elements.

2022-01-19 08:12 UTC, mmagician commented
Thanks for a quick response. I'm still seeing warnings from both:
`cargo clippy` and `cargo fmt --all --check`. Just by skimming through clippy issues, it seems like you can still fix a few of these. Format should definitely be fixed though.
Regarding tests: if it already works with larger inputs, then I guess it shouldn't be a problem to make the tests more realistic?

Thanks for your cooperation.

2022-01-21 04:52 UTC, lornacrevelingwgo23 commented
> Thanks for a quick response. I'm still seeing warnings from both: `cargo clippy` and `cargo fmt --all --check`. Just by skimming through clippy issues, it seems like you can still fix a few of these. Format should definitely be fixed though. Regarding tests: if it already works with larger inputs, then I guess it shouldn't be a problem to make the tests more realistic?
> 
> Thanks for your cooperation.

Thanks for your comments. We have tried our best to remove the remaining clippy and format issues. We also test our code with additional cases with vectors of sizes 10, 50, and 100. Please check the [repo](https://github.com/rubyprotocol/Ruby_milestone2) for the update.

2022-01-25 04:39 UTC, lornacrevelingwgo23 commented
Hey @mmagician, please leave a message if there is any other issue. We are more than happy to revise the code accordingly.

2022-01-25 14:49 UTC, mmagician commented
@lornacrevelingwgo23 I will do another round of tests later on and let you know.

2022-02-03 14:44 UTC, HLin2014 commented
> @lornacrevelingwgo23 I will do another round of tests later on and let you know.

Hey @mmagician , any news from your side? We look forward to the next step. Thanks.

2022-02-06 11:54 UTC, mmagician commented
I will try my best to do another round of reviews in the upcoming week.
Thank you for the patience!

2022-02-09 10:29 UTC, takahser commented
Hi @lornacrevelingwgo23 
FYI - Regarding the review, I'm taking over from here.
Please allow for some time, I'll get back to you with my feedback soon.

2022-02-09 22:21 UTC, takahser commented
Hi @lornacrevelingwgo23 

Unfortunately there are still a lot of issues when running `cargo clippy`.

```bash
% cargo clippy           
warning: the loop variable `i` is used to index `fe_key`
   --> src/dmcfe_ip.rs:106:22
    |
106 |             for i in 0..2 {
    |                      ^^^^
    |
    = note: `#[warn(clippy::needless_range_loop)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
106 |             for (i, <item>) in fe_key.iter_mut().enumerate().take(2) {
    |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is used to index `pub_keys`
   --> src/dmcfe_ip.rs:189:18
    |
189 |         for i in 0..pub_keys.len() {
    |                  ^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
189 |         for (i, <item>) in pub_keys.iter().enumerate() {
    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is only used to index `x`
   --> src/dmcfe_ip.rs:247:18
    |
247 |         for i in 0..x.len() {
    |                  ^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
247 |         for <item> in &x {
    |             ~~~~~~    ~~

warning: the loop variable `i` is used to index `hs`
   --> src/dmcfe_ip.rs:269:18
    |
269 |         for i in 0..2 {
    |                  ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
269 |         for (i, <item>) in hs.iter_mut().enumerate().take(2) {
    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is used to index `fe_key_share`
   --> src/dmcfe_ip.rs:278:18
    |
278 |         for i in 0..2 {
    |                  ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
278 |         for (i, <item>) in fe_key_share.iter_mut().enumerate().take(2) {
    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `j` is used to index `hs`
   --> src/dmcfe_ip.rs:280:22
    |
280 |             for j in 0..2 {
    |                      ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
280 |             for (j, <item>) in hs.iter().enumerate().take(2) {
    |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is only used to index `keys_sum`
   --> src/dmcfe_ip.rs:307:18
    |
307 |         for i in 0..2 {
    |                  ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
307 |         for <item> in keys_sum.iter_mut().take(2) {
    |             ~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `j` is used to index `keys_sum`
   --> src/dmcfe_ip.rs:312:22
    |
312 |             for j in 0..2 {
    |                      ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
312 |             for (j, <item>) in keys_sum.iter_mut().enumerate().take(2) {
    |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices
   --> src/dmcfe_ip.rs:337:18
    |
337 |         ciphers: &G1Vector,
    |                  ^^^^^^^^^
    |
    = note: `#[warn(clippy::ptr_arg)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

warning: the loop variable `i` is used to index `ciphers`
   --> src/dmcfe_ip.rs:349:18
    |
349 |         for i in 0..L {
    |                  ^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
349 |         for (i, <item>) in ciphers.iter().enumerate().take(L) {
    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices
  --> src/ml/disease_prediction.rs:81:36
   |
81 |     pub fn compute(&self, ciphers: &G1Vector) -> Vec<f32> {
   |                                    ^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

warning: the loop variable `i` is used to index `v`
  --> src/simple_ip.rs:39:18
   |
39 |         for i in 0..L {
   |                  ^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
   |
39 |         for (i, <item>) in v.iter_mut().enumerate().take(L) {
   |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is used to index `x`
   --> src/utils/mod.rs:217:14
    |
217 |     for i in 0..x.len() {
    |              ^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
217 |     for (i, <item>) in x.iter().enumerate() {
    |         ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `j` is used to index `y`
   --> src/utils/mod.rs:218:18
    |
218 |         for j in 0..y.len() {
    |                  ^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
218 |         for (j, <item>) in y.iter().enumerate() {
    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~

warning: `ruby` (lib) generated 14 warnings
warning: the loop variable `i` is used to index `v`
  --> src/bin/owner.rs:58:14
   |
58 |     for i in 0..L {
   |              ^^^^
   |
   = note: `#[warn(clippy::needless_range_loop)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
   |
58 |     for (i, <item>) in v.iter_mut().enumerate().take(L) {
   |         ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: field is never read: `ipsk`
   --> src/bin/authority.rs:118:5
    |
118 |     ipsk: Arc<RwLock<IpSk>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field is never read: `quask`
   --> src/bin/authority.rs:119:5
    |
119 |     quask: Arc<RwLock<QuaSK>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `ippk`
   --> src/bin/authority.rs:123:5
    |
123 |     ippk: Arc<RwLock<HashMap<i32, String>>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: the loop variable `i` is used to index `c`
   --> src/bin/authority.rs:162:14
    |
162 |     for i in 0..L {
    |              ^^^^
    |
    = note: `#[warn(clippy::needless_range_loop)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
help: consider using an iterator
    |
162 |     for (i, <item>) in c.iter_mut().enumerate().take(L) {
    |         ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

warning: the loop variable `i` is used to index `_y`
   --> src/bi [...]

2022-02-10 02:41 UTC, lornacrevelingwgo23 commented
> Hi @lornacrevelingwgo23
> 
> Unfortunately there are still a lot of issues when running `cargo clippy`.
> 
> ```shell
> % cargo clippy           
> warning: the loop variable `i` is used to index `fe_key`
>    --> src/dmcfe_ip.rs:106:22
>     |
> 106 |             for i in 0..2 {
>     |                      ^^^^
>     |
>     = note: `#[warn(clippy::needless_range_loop)]` on by default
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 106 |             for (i, <item>) in fe_key.iter_mut().enumerate().take(2) {
>     |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `i` is used to index `pub_keys`
>    --> src/dmcfe_ip.rs:189:18
>     |
> 189 |         for i in 0..pub_keys.len() {
>     |                  ^^^^^^^^^^^^^^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 189 |         for (i, <item>) in pub_keys.iter().enumerate() {
>     |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `i` is only used to index `x`
>    --> src/dmcfe_ip.rs:247:18
>     |
> 247 |         for i in 0..x.len() {
>     |                  ^^^^^^^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 247 |         for <item> in &x {
>     |             ~~~~~~    ~~
> 
> warning: the loop variable `i` is used to index `hs`
>    --> src/dmcfe_ip.rs:269:18
>     |
> 269 |         for i in 0..2 {
>     |                  ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 269 |         for (i, <item>) in hs.iter_mut().enumerate().take(2) {
>     |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `i` is used to index `fe_key_share`
>    --> src/dmcfe_ip.rs:278:18
>     |
> 278 |         for i in 0..2 {
>     |                  ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 278 |         for (i, <item>) in fe_key_share.iter_mut().enumerate().take(2) {
>     |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `j` is used to index `hs`
>    --> src/dmcfe_ip.rs:280:22
>     |
> 280 |             for j in 0..2 {
>     |                      ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 280 |             for (j, <item>) in hs.iter().enumerate().take(2) {
>     |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `i` is only used to index `keys_sum`
>    --> src/dmcfe_ip.rs:307:18
>     |
> 307 |         for i in 0..2 {
>     |                  ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 307 |         for <item> in keys_sum.iter_mut().take(2) {
>     |             ~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `j` is used to index `keys_sum`
>    --> src/dmcfe_ip.rs:312:22
>     |
> 312 |             for j in 0..2 {
>     |                      ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 312 |             for (j, <item>) in keys_sum.iter_mut().enumerate().take(2) {
>     |                 ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices
>    --> src/dmcfe_ip.rs:337:18
>     |
> 337 |         ciphers: &G1Vector,
>     |                  ^^^^^^^^^
>     |
>     = note: `#[warn(clippy::ptr_arg)]` on by default
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
> 
> warning: the loop variable `i` is used to index `ciphers`
>    --> src/dmcfe_ip.rs:349:18
>     |
> 349 |         for i in 0..L {
>     |                  ^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 349 |         for (i, <item>) in ciphers.iter().enumerate().take(L) {
>     |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices
>   --> src/ml/disease_prediction.rs:81:36
>    |
> 81 |     pub fn compute(&self, ciphers: &G1Vector) -> Vec<f32> {
>    |                                    ^^^^^^^^^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
> 
> warning: the loop variable `i` is used to index `v`
>   --> src/simple_ip.rs:39:18
>    |
> 39 |         for i in 0..L {
>    |                  ^^^^
>    |
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>    |
> 39 |         for (i, <item>) in v.iter_mut().enumerate().take(L) {
>    |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `i` is used to index `x`
>    --> src/utils/mod.rs:217:14
>     |
> 217 |     for i in 0..x.len() {
>     |              ^^^^^^^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 217 |     for (i, <item>) in x.iter().enumerate() {
>     |         ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~
> 
> warning: the loop variable `j` is used to index `y`
>    --> src/utils/mod.rs:218:18
>     |
> 218 |         for j in 0..y.len() {
>     |                  ^^^^^^^^^^
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>     |
> 218 |         for (j, <item>) in y.iter().enumerate() {
>     |             ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~
> 
> warning: `ruby` (lib) generated 14 warnings
> warning: the loop variable `i` is used to index `v`
>   --> src/bin/owner.rs:58:14
>    |
> 58 |     for i in 0..L {
>    |              ^^^^
>    |
>    = note: `#[warn(clippy::needless_range_loop)]` on by default
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_range_loop
> help: consider using an iterator
>    |
> 58 |     for (i, <item>) in v.iter_mut().enumerate().take(L) {
>    |         ~~~~~~~~~~~    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> warning: field is never read: `ipsk`
>    --> src/bin/authority.rs:118:5
>     |
> 118 |     ipsk: Arc<RwLock<IpSk>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: `#[warn(dead_code)]` on by default
> 
> warning: field is never read: `quask`
>    --> src/bin/authority.rs:119:5
>     |
> 119 |     quask: Arc<RwLock<QuaSK>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: field is never read: `ippk`
>    --> src/bin/authority.rs:123:5
>     |
> 123 |     ippk: Arc<RwLock<HashMap<i32, String>>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: the loop variable `i` is used to index `c`
>    --> src/bin/authority.rs:162:14
>     |
> 162 |     for i in 0..L {
>     |              ^^^^
>     |
> [...]

2022-02-10 07:39 UTC, takahser commented
Hey @lornacrevelingwgo23 
That's great. Please let me know when your code is ready so I can do another iteration of the review.

2022-02-10 07:51 UTC, lornacrevelingwgo23 commented
> Hey @lornacrevelingwgo23 That's great. Please let me know when your code is ready so I can do another iteration of the review.

Sure, will do.

2022-02-17 00:36 UTC, lornacrevelingwgo23 commented
> Hey @lornacrevelingwgo23 That's great. Please let me know when your code is ready so I can do another iteration of the review.

Hey @takahser, already updated the [repo](https://github.com/rubyprotocol/Ruby_milestone2). The mentioned issues have been fixed. Please check it out.

2022-02-22 02:05 UTC, lornacrevelingwgo23 commented
> > Hey @lornacrevelingwgo23 That's great. Please let me know when your code is ready so I can do another iteration of the review.
> 
> Hey @takahser, already updated the [repo](https://github.com/rubyprotocol/Ruby_milestone2). The mentioned issues have been fixed. Please check it out.

Hey @takahser , we look forward to your comments on our latest update. Thanks.

2022-02-22 09:26 UTC, takahser commented
Hey @lornacrevelingwgo23 
Thanks for the update!
Apologies from my side, it's been busy recently, so it might take some time until I have the capacity to have a look at your changes
Thanks for your understanding and patience 👍

2022-03-06 05:32 UTC, HLin22 commented
> Hey @lornacrevelingwgo23 Thanks for the update! Apologies from my side, it's been busy recently, so it might take some time until I have the capacity to have a look at your changes Thanks for your understanding and patience 👍

Hey @takahser , any chance you find time to review the update recently? Please let us know. Thanks.

2022-03-07 05:48 UTC, lornacrevelingwgo23 commented
> Hey @lornacrevelingwgo23 Thanks for the update! Apologies from my side, it's been busy recently, so it might take some time until I have the capacity to have a look at your changes Thanks for your understanding and patience 👍

Hey @takahser , any chance you find time to review the update recently? Please let us know. Thanks.

2022-03-07 10:30 UTC, takahser commented
@lornacrevelingwgo23 thanks a lot for your patience and apologies from my side, it's been busy lately.
I checked out your latest revision `511a2c3ed6ea7e0fdff7fd6657fcd8f4f5627bd5` and, if I'm not mistaken, I still see a couple of warnings that could easily be fixed. Can you take another look?

```bash
% cargo clippy

(...)

warning: `to_string` applied to a type that implements `Display` in `format!` args
  --> src/dmcfe_ip.rs:97:46
   |
97 |             let ex_label = format!("{} {}", i.to_string(), y_str);
   |                                              ^^^^^^^^^^^^ help: remove this
   |
   = note: `#[warn(clippy::to_string_in_format_args)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args

warning: `to_string` applied to a type that implements `Display` in `format!` args
   --> src/dmcfe_ip.rs:232:46
    |
232 |             let ex_label = format!("{} {}", i.to_string(), label);
    |                                              ^^^^^^^^^^^^ help: remove this
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args

warning: `to_string` applied to a type that implements `Display` in `format!` args
   --> src/dmcfe_ip.rs:270:46
    |
270 |             let ex_label = format!("{} {}", i.to_string(), y_str);
    |                                              ^^^^^^^^^^^^ help: remove this
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args

warning: `to_string` applied to a type that implements `Display` in `format!` args
   --> src/dmcfe_ip.rs:364:46
    |
364 |             let ex_label = format!("{} {}", i.to_string(), label);
    |                                              ^^^^^^^^^^^^ help: remove this
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args

warning: `ruby` (lib) generated 4 warnings
warning: field is never read: `ipsk`
   --> src/bin/authority.rs:119:5
    |
119 |     ipsk: Arc<RwLock<IpSk>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: field is never read: `quask`
   --> src/bin/authority.rs:120:5
    |
120 |     quask: Arc<RwLock<QuaSK>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `ippk`
   --> src/bin/authority.rs:124:5
    |
124 |     ippk: Arc<RwLock<HashMap<i32, String>>>,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `ruby` (bin "authority-api") generated 3 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 31.92s
```

2022-03-07 10:30 UTC, takahser requested changes
See my latest comment ⬆️

2022-03-07 12:32 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks a lot for your patience and apologies from my side, it's been busy lately. I checked out your latest revision `511a2c3ed6ea7e0fdff7fd6657fcd8f4f5627bd5` and, if I'm not mistaken, I still see a couple of warnings that could easily be fixed. Can you take another look?
> 
> ```shell
> % cargo clippy
> 
> (...)
> 
> warning: `to_string` applied to a type that implements `Display` in `format!` args
>   --> src/dmcfe_ip.rs:97:46
>    |
> 97 |             let ex_label = format!("{} {}", i.to_string(), y_str);
>    |                                              ^^^^^^^^^^^^ help: remove this
>    |
>    = note: `#[warn(clippy::to_string_in_format_args)]` on by default
>    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args
> 
> warning: `to_string` applied to a type that implements `Display` in `format!` args
>    --> src/dmcfe_ip.rs:232:46
>     |
> 232 |             let ex_label = format!("{} {}", i.to_string(), label);
>     |                                              ^^^^^^^^^^^^ help: remove this
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args
> 
> warning: `to_string` applied to a type that implements `Display` in `format!` args
>    --> src/dmcfe_ip.rs:270:46
>     |
> 270 |             let ex_label = format!("{} {}", i.to_string(), y_str);
>     |                                              ^^^^^^^^^^^^ help: remove this
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args
> 
> warning: `to_string` applied to a type that implements `Display` in `format!` args
>    --> src/dmcfe_ip.rs:364:46
>     |
> 364 |             let ex_label = format!("{} {}", i.to_string(), label);
>     |                                              ^^^^^^^^^^^^ help: remove this
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#to_string_in_format_args
> 
> warning: `ruby` (lib) generated 4 warnings
> warning: field is never read: `ipsk`
>    --> src/bin/authority.rs:119:5
>     |
> 119 |     ipsk: Arc<RwLock<IpSk>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: `#[warn(dead_code)]` on by default
> 
> warning: field is never read: `quask`
>    --> src/bin/authority.rs:120:5
>     |
> 120 |     quask: Arc<RwLock<QuaSK>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: field is never read: `ippk`
>    --> src/bin/authority.rs:124:5
>     |
> 124 |     ippk: Arc<RwLock<HashMap<i32, String>>>,
>     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> warning: `ruby` (bin "authority-api") generated 3 warnings
>     Finished dev [unoptimized + debuginfo] target(s) in 31.92s
> ```

Hey @takahser , thanks for your comments. Will get back to you soon on this.

2022-03-08 05:53 UTC, lornacrevelingwgo23 commented
Hey @takahser, already updated the [repo](https://github.com/rubyprotocol/Ruby_milestone2). The mentioned warnings have been fixed. Please check it out.

2022-03-09 09:06 UTC, lornacrevelingwgo23 approved these changes

2022-03-14 11:58 UTC, takahser commented
@lornacrevelingwgo23 thanks for fixing, I confirm that there are no clippy issues anymore. Next, I'm planning to take a closer look at your delivery and be back with more detailed feedback soon.

2022-03-17 01:39 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for fixing, I confirm that there are no clippy issues anymore. Next, I'm planning to take a closer look at your delivery and be back with more detailed feedback soon.

Great, looking forward to hearing from you again.

2022-03-21 00:39 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for fixing, I confirm that there are no clippy issues anymore. Next, I'm planning to take a closer look at your delivery and be back with more detailed feedback soon.

Hey @takahser , any update from your side on the feedback? Thanks.

2022-03-23 00:58 UTC, lornacrevelingwgo23 commented
> Hi @lornacrevelingwgo23 Sorry for the delay here. I checked out your project and followed the instructions in your [README](https://github.com/rubyprotocol/Ruby_milestone2/blob/11bcb1e59d8abbc4c093d5ce9e772f2df90f9753/README.md).
> 
> I was able to run the following services:
> 
> * Authority API Service
> * Data Owner API Service
> 
> But they'd both return a `405 Method Not Allowed`: <img alt="image" width="183" src="https://user-images.githubusercontent.com/5393704/159450433-2896b3c1-ce85-46fa-87fa-333d5ae32bbe.png">
> 
> I also tried to run:
> 
> * Data Purchaser API Service
> 
> But that service doesn't even respond in the first place. I'm not sure, why the services are not working. Do I miss something?
> 
> Also, I tried to set up the [zero-pool-node](https://github.com/rubyprotocol/Ruby_milestone2/blob/f060d9fabe9a61245d95cb7caab2f8f8186725d1/README.md?plain=1#L57) according to your M1 Readme but apparently, the folder mentioned isn't available in the most recent revision of the repo. Could you guide me through the process on how to run the node and ideally also update these instructions?

Thanks for the comments. I think the main issue is that the zeropool node is not set up correctly. The [readme](https://github.com/rubyprotocol/Ruby_milestone2/blob/f060d9fabe9a61245d95cb7caab2f8f8186725d1/README.md?plain=1#L57) you referred to belongs to a fork branch of milestone2 repo, which does not include our latest update on the setup instruction. Please follow the [readme](https://github.com/rubyprotocol/Ruby_milestone2/blob/main/README.md) in the main branch to set up the zeropool node.

After building the API service, run the authority, data owner, and data purchaser's API and then keep all the three terminals open and run the Ruby frontend. When the dev nodes are running correctly, you can start to test the API on the frontend according to the instruction in [tutorial](https://github.com/rubyprotocol/Ruby_milestone2/blob/main/tutorial.md). Please let me know if you have any other questions.

2022-03-23 08:20 UTC, takahser commented
@lornacrevelingwgo23 thanks for clarifying. I tried setting up the zeropool node using the updated instructions, however it fails:

```bash
% make init
./scripts/init.sh
*** Initializing WASM build environment
info: syncing channel updates for 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.61.0-nightly (5f3700105 2022-03-22)

info: checking for self-updates
info: syncing channel updates for 'nightly-2020-10-05-aarch64-apple-darwin'
info: latest update on 2020-10-05, rust version 1.49.0-nightly (beb5ae474 2020-10-04)
error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
make: *** [init] Error 1
```

I'm using a MacBook Air (M1, 2020) running on MacOs 12.2.1

2022-03-23 10:54 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for clarifying. I tried setting up the zeropool node using the updated instructions, however it fails:
> 
> ```shell
> % make init
> ./scripts/init.sh
> *** Initializing WASM build environment
> info: syncing channel updates for 'nightly-aarch64-apple-darwin'
> 
>   nightly-aarch64-apple-darwin unchanged - rustc 1.61.0-nightly (5f3700105 2022-03-22)
> 
> info: checking for self-updates
> info: syncing channel updates for 'nightly-2020-10-05-aarch64-apple-darwin'
> info: latest update on 2020-10-05, rust version 1.49.0-nightly (beb5ae474 2020-10-04)
> error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
> make: *** [init] Error 1
> ```
> 
> I'm using a MacBook Air (M1, 2020) running on MacOs 12.2.1

It's possible that your problem is caused by the M1 chip of your MacBook. Would you please try to set up the zeropool node using either a MacBook with an intel chip or maybe a Ubuntu system?

2022-03-27 11:02 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for clarifying. I tried setting up the zeropool node using the updated instructions, however it fails:
> 
> ```shell
> % make init
> ./scripts/init.sh
> *** Initializing WASM build environment
> info: syncing channel updates for 'nightly-aarch64-apple-darwin'
> 
>   nightly-aarch64-apple-darwin unchanged - rustc 1.61.0-nightly (5f3700105 2022-03-22)
> 
> info: checking for self-updates
> info: syncing channel updates for 'nightly-2020-10-05-aarch64-apple-darwin'
> info: latest update on 2020-10-05, rust version 1.49.0-nightly (beb5ae474 2020-10-04)
> error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
> make: *** [init] Error 1
> ```
> 
> I'm using a MacBook Air (M1, 2020) running on MacOs 12.2.1

Please check this [post](https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html#support-for-apple-m1-devices). Only the rust version released after Nov. 27th, 2020 supports M1. We have updated the init file to ensure it is compatible with M1. Please follow the instruction in the [readme](https://github.com/rubyprotocol/Ruby_milestone2/blob/main/README.md) and see if it works this time.

2022-03-28 12:58 UTC, takahser commented
@lornacrevelingwgo23 thanks for the update.
`make init` now succeeds with the new instructions, but `make run` fails with:

```bash
% make run

cargo +nightly-2020-10-05 build --release 
error: toolchain 'nightly-2020-10-05-aarch64-apple-darwin' is not installed
make: *** [run] Error 1
```

I tried installing the missing toolchain but that also failed:

```bash
% rustup toolchain add nightly-2020-10-05-aarch64-apple-darwin
info: syncing channel updates for 'nightly-2020-10-05-aarch64-apple-darwin'
info: latest update on 2020-10-05, rust version 1.49.0-nightly (beb5ae474 2020-10-04)
error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
```

2022-03-29 03:05 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for the update. `make init` now succeeds with the new instructions, but `make run` fails with:
> 
> ```shell
> % make run
> 
> cargo +nightly-2020-10-05 build --release 
> error: toolchain 'nightly-2020-10-05-aarch64-apple-darwin' is not installed
> make: *** [run] Error 1
> ```
> 
> I tried installing the missing toolchain but that also failed:
> 
> ```shell
> % rustup toolchain add nightly-2020-10-05-aarch64-apple-darwin
> info: syncing channel updates for 'nightly-2020-10-05-aarch64-apple-darwin'
> info: latest update on 2020-10-05, rust version 1.49.0-nightly (beb5ae474 2020-10-04)
> error: target 'aarch64-apple-darwin' not found in channel.  Perhaps check https://doc.rust-lang.org/nightly/rustc/platform-support.html for available targets
> ```

Hey @takahser , we have tried to update the Rust version to the one released after November, but the zeropool pallet cannot pass the compilation with this rust version. It seems the zeropool pallet only supports the rust version before October. On the other hand, the earliest possible Rust that supports M1 is the one released after November. You can see the kind of dilemma we are currently in. 

Would you please switch to a Macbook with an intel core or maybe a server with a ubuntu system if it's not too much trouble? My own Macbook has an intel core and it works perfectly well with the zeropool pallet, and my other teammate's computer has a ubuntu system and it also works OK. Please consider this option. Thanks a lot.

2022-04-03 13:38 UTC, lornacrevelingwgo23 commented
> Hey @takahser

Hey @takahser, I don't think there is any way we could make Ruby compatible with M1 Macbook at the moment unless the zeropool folks somehow work things out. That's why I've set up a server with Linux system and I've test the [zeropool](https://github.com/lornacrevelingwgo23/zeropool_substrate_fork/blob/main/README.md) code myself on it, and it works perfectly well. Would you please send me your email address so that I can send you the password and IP of the Linux server so that you could test Ruby protocol on the server? Thanks.

2022-04-04 11:11 UTC, takahser commented
@lornacrevelingwgo23 thanks for your efforts. Yes, under this circumstances it might be easier to solve this via chat/email. I've reached out to you via [email](info@ruby.io).

2022-04-05 03:34 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for your efforts. Yes, under this circumstances it might be easier to solve this via chat/email. I've reached out to you via [email](mailto:info@ruby.io).



> 

Hey @takahser , I've already left you a message via Matrix with the info regarding the IP and password of Linux server. Feel free to leave a message there if you have any problem.

2022-04-22 15:03 UTC, takahser commented
@lornacrevelingwgo23 thanks for the call yesterday, it was really helpful and the infrastructure now works for me. 👍
However, I just realized that in your delivery some deliverables are missing. The 0b., 0c. seem to be missing and also 1. and 2. do not match the deliverables from [your contract](https://github.com/w3f/Grants-Program/blob/916cdd52d3f631e829c00fae1431186f8dc7859d/applications/RubyProtocol.md#milestone-2--client-implementation-and-integration). Could you consolidate the deliverables such that they match with these you declared in that grant application? Let me know if anything is unclear.

2022-04-23 07:36 UTC, rubyprotocol commented
> @lornacrevelingwgo23 thanks for the call yesterday, it was really helpful and the infrastructure now works for me. 👍 However, I just realized that in your delivery some deliverables are missing. The 0b., 0c. seem to be missing and also 1. and 2. do not match the deliverables from [your contract](https://github.com/w3f/Grants-Program/blob/916cdd52d3f631e829c00fae1431186f8dc7859d/applications/RubyProtocol.md#milestone-2--client-implementation-and-integration). Could you consolidate the deliverables such that they match with these you declared in that grant application? Let me know if anything is unclear.

Thanks for your comments. Already updated the [delivery](https://github.com/Ruby-Protocol/Grant-Milestone-Delivery/blob/master/deliveries/ruby_milestone_2.md) accordingly.

2022-04-25 08:03 UTC, takahser commented
@rubyprotocol thanks for the update, 0a.-0d. are fine now. 👍
However, 1-3 are still missing and the 1 in the delivery seems to be a different deliverable?! Instead of "Client modules" it's called "Personal data monetization framework based on functional encryption and substrate pallet". Also, "2. | Benchmark" and "3. | Docker" are missing, correct?

2022-05-03 09:17 UTC, takahser requested changes
@lornacrevelingwgo23 Thx for the update, it looks much better indeed. However, I just realized that the [LICENSE files](https://www.apache.org/licenses/LICENSE-2.0#apply) are missing in your repos. Keep in mind that you need to include it in case of an APACHE 2.0 license.

2022-05-03 13:57 UTC, lornacrevelingwgo23 commented
> delivery

Hey, thanks for your reminder. Already include the APACHE 2.0 license and notice in our [delivery](https://github.com/rubyprotocol/Ruby_milestone2).

2022-05-03 13:58 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 Thx for the update, it looks much better indeed. However, I just realized that the [LICENSE files](https://www.apache.org/licenses/LICENSE-2.0#apply) are missing in your repos. Keep in mind that you need to include it in case of an APACHE 2.0 license.

Hey @takahser , thanks for your reminder. Already include the APACHE 2.0 license and notice in our [delivery](https://github.com/rubyprotocol/Ruby_milestone2).

2022-05-06 04:30 UTC, takahser requested changes
@lornacrevelingwgo23 thanks for adding the LICENSE file. Could you also add it to the [other repo](https://github.com/lornacrevelingwgo23/zeropool_substrate_fork/tree/0af69c79704c10bdb56601766fada4629f250c20) you referenced in your delivery?

2022-05-06 06:53 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for adding the LICENSE file. Could you also add it to the [other repo](https://github.com/lornacrevelingwgo23/zeropool_substrate_fork/tree/0af69c79704c10bdb56601766fada4629f250c20) you referenced in your delivery?

Sure, already added the LICENSE files to all the repo mentioned in the [delivery](https://github.com/Ruby-Protocol/Grant-Milestone-Delivery/blob/master/deliveries/ruby_milestone_2.md). Please check it out.

2022-05-09 04:52 UTC, takahser approved these changes
@lornacrevelingwgo23 thanks for adding the LICENSE file to the zeropool repo as well. I've accepted the delivery, you can find my evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ruby_protocol_2_takahser.md

2022-05-09 04:52 UTC, merged

2022-05-09 08:16 UTC, lornacrevelingwgo23 commented
> @lornacrevelingwgo23 thanks for adding the LICENSE file to the zeropool repo as well. I've accepted the delivery, you can find my evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ruby_protocol_2_takahser.md

Cool, thanks a lot.

2022-05-16 15:40 UTC, RouvenP commented
hi @lornacrevelingwgo23 we transferred the payment today. Thanks!