Evaluation of RainbowDAO, Milestone 1 - round 1
w3f/Grant-Milestone-Delivery pull request #339
Opened 2022-01-14 14:42 UTC by takahser

Evaluation for the RainbowDAO, Milestone 1 delivery https://github.com/w3f/Grant-Milestone-Delivery/pull/334

2022-01-14 14:52 UTC, mmagician requested changes
Since there are a lot of warnings / things half-working, maybe just inform the team (and add into the evaluation) that it's fine for this Milestone, but that they'll be required to address all these minor issues for acceptance of M2.

2022-01-14 16:14 UTC, mmagician approved these changes

2022-01-15 02:34 UTC, RainbowcityKun commented
> Since there are a lot of warnings / things half-working, maybe just inform the team (and add into the evaluation) that it's fine for this Milestone, but that they'll be required to address all these minor issues for acceptance of M2.

@takahser , @mmagician ,
Thanks to @takahser for the careful evaluation of our first milestone submission, it also made us realize that there are a lot of small issues, we will double check based on the content of the evaluation report. When committing to milestone 2, we'll tackle all the minor issues together.

2022-01-17 09:32 UTC, Noc2 approved these changes

2022-01-17 09:32 UTC, merged