create the delivery file
w3f/Grant-Milestone-Delivery pull request #388
Opened 2022-03-05 11:58 UTC by woss

Signed-off-by: Daniel Maricic <daniel@woss.io>

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/719 < please fill this in with the PR number of your application.

2022-03-05 15:39 UTC, alxs requested changes

2022-03-05 15:39 UTC, alxs commented on deliveries/anagolay-project-idiyanale-phase-1.md
> +-   **Application Document:** https://github.com/w3f/Grants-Program/pull/719
```suggestion
-   **Application Document:** https://github.com/w3f/Grants-Program/blob/master/applications/anagolay-project-idiyanale-phase-1.md
```

2022-03-05 15:40 UTC, alxs commented
Thank you for the deliver @woss. We'll look into it as soon as possible.

2022-03-11 09:54 UTC, Noc2 approved these changes
Sorry for the delay here. I’m happy to confirm that everything is working and that the milestone is a pass. Thanks for the very good delivery. I will forward your invoice internally.

2022-03-11 09:54 UTC, merged

2022-03-21 11:24 UTC, woss commented
Hi @Noc2, just a follow-up, is everything ok with the invoice? If your guys have sent the Milestone 1 payment I didn't receive anything yet, if they didn't do you mind telling me when I can expect the payment?

Thanks

2022-03-21 12:07 UTC, takahser commented
@woss I'm sorry to hear that, I asked our finance team to double-check. Somebody will reach out to you soon. Please don't hesitate to ask further questions.

2022-03-22 12:30 UTC, RouvenP commented
hi @woss we transferred the payment today. Thanks!

2022-03-22 13:54 UTC, woss commented
@RouvenP got it :) thanks