Gafi Milestone 1 PR
w3f/Grant-Milestone-Delivery pull request #422
Opened 2022-04-16 04:12 UTC by mutobui

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

2022-04-20 07:47 UTC, takahser requested changes
The checks probably failed because you linked the PR instead of the application doc:)

2022-04-20 07:47 UTC, takahser commented on deliveries/Gafi-milestone_1.md
> +* **Application Document:** https://github.com/w3f/Grants-Program/pull/896
```suggestion
* **Application Document:** https://github.com/w3f/Grants-Program/blob/master/applications/Gafi.md
```
```suggestion
* **Application Document:** https://github.com/w3f/Grants-Program/pull/896
```

2022-04-20 09:19 UTC, takahser commented
@mutobui perfect, now the checks succeeded.
Anyway, thanks for the delivery. We will look into it (in more detail) as soon as possible. 👍

2022-04-20 09:37 UTC, mutobui commented
> @mutobui perfect, now the checks succeeded. Anyway, thanks for the delivery. We will look into it (in more detail) as soon as possible. 👍

Thank you, excited to wait for your advice. We are willing to the changes.

2022-04-22 18:10 UTC, Noc2 approved these changes
I’m happy to tell you that the milestone is a pass. Keegan evaluated your delivery and was really happy with it: https://github.com/keeganquigley/Grant-Milestone-Delivery/pull/1 Everything immediately worked and the code looks good. I will forward your invoice internally.

2022-04-22 18:10 UTC, merged

2022-04-23 04:20 UTC, mutobui commented
Thank you @Noc2 @takahser @keeganquigley and web3 foundation team for your relentless support, this first milestone will give us more resources to build Gafi Network and the web3 mission.

2022-05-02 15:32 UTC, RouvenP commented
hi @mutobui we transferred the payment today. Thanks!