Deliver OpenSquare paid QA spec 1.0 implementation
w3f/Grant-Milestone-Delivery pull request #496
Opened 2022-07-12 06:14 UTC by wliyongfeng

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

2022-07-12 11:53 UTC, lucasvanmol commented
Hey @wliyongfeng, could you provide instructions on how to setup a local ipfs node instead of using infura? Infura requires entering credit card information even for free projects, so I'd rather setup a local ipfs node instead.

2022-07-14 08:25 UTC, lucasvanmol requested changes
You seem to have some typos here, could you please fix them? Thanks

2022-07-14 08:41 UTC, wliyongfeng commented on deliveries/OpenSquare_paid_qa-milestone_1.md
> +| 0c. | Documentation | https://github.com/opensquare-network/paid-qa/discussions/697 | [spec repo](https://github.com/opensquare-network/qa-spec) and another [tutorial](https://hackmd.io/@WIq3uV0rRw
Fixed, thank you.

2022-07-14 09:33 UTC, lucasvanmol commented
Hey there, I'm trying to visit https://review-paid-qa.on.fleek.co/ again, but am being met with the following, even though it was working fine yesterday:
![Screenshot 2022-07-14 at 11 27 57](https://user-images.githubusercontent.com/16979353/178950730-dd065983-4e26-4bf7-8ba6-b14fba8f8df7.png)

2022-07-14 09:48 UTC, wliyongfeng commented
> Hey there, I'm trying to visit https://review-paid-qa.on.fleek.co/ again, but am being met with the following, even though it was working fine yesterday

Weird, it works well on my side. Ok, I'll deploy another environment. I'll let you know when it's ready.

2022-07-14 10:06 UTC, wliyongfeng commented
@lucasvanmol Please visit https://review-paid-qa.opensquare.io if https://review-paid-qa.on.fleek.co is still unavailable.

2022-07-14 10:17 UTC, lucasvanmol commented
@wliyongfeng Thanks a lot for this! It looks like I can connect to both just fine now, however, so it may have just been a temporary problem. I'm now trying to run the project locally, but running into some problems: I'll share them in the matrix opensquare matrix channel.

2022-07-14 10:36 UTC, wliyongfeng commented
> @wliyongfeng Thanks a lot for this! It looks like I can connect to both just fine now, however, so it may have just been a temporary problem. I'm now trying to run the project locally, but running into some problems: I'll share them in the opensquare matrix channel.

Have replied in the cannel. It's a MongoDB [replica set](https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/) setting problem. We need this to keep some business transactional and will add this configuration warning to the README.

2022-07-15 11:00 UTC, lucasvanmol commented
Thanks again @wliyongfeng for the assisstance on element. I've accepted the delivery - please take a look at my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/opensquare-paid-qa_m1_lucasvanmol.md). I'll also forward your invoice internally.

2022-07-15 11:00 UTC, merged

2022-07-28 11:02 UTC, RouvenP commented
hi @wliyongfeng, we transferred the payment yesterday. Thanks!

2022-07-28 13:39 UTC, wliyongfeng commented
> hi @wliyongfeng, we transferred the payment yesterday. Thanks!

@RouvenP Confirmed. Thanks!