Faceless-milestone2.md
w3f/Grant-Milestone-Delivery pull request #655
Opened 2022-12-12 03:07 UTC by HeisenbergLin22

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

2022-12-12 13:35 UTC, alxs commented
Thanks for the delivery @HeisenbergLin22. We'll look into it as soon as possible. In the meantime, could you please:

- Make sure you're creating a new file for your delivery instead of modifying the template
- Read your first comment above and tick all checkboxes that apply
- Check your Dockerfile - the build is failing for me: [docker.txt](https://github.com/w3f/Grant-Milestone-Delivery/files/10208392/docker.txt)

2022-12-13 05:21 UTC, HeisenbergLin22 commented
> Thanks for the delivery @HeisenbergLin22. We'll look into it as soon as possible. In the meantime, could you please:
> 
> * Make sure you're creating a new file for your delivery instead of modifying the template
> * Read your first comment above and tick all checkboxes that apply
> * Check your Dockerfile - the build is failing for me: [docker.txt](https://github.com/w3f/Grant-Milestone-Delivery/files/10208392/docker.txt)

Hey @alxs , thanks for your comments. I have already created a [new file](https://github.com/FacelessProject/Faceless-Grant-Milestone2-Delivery/blob/master/Faceless-milestone2.md) for the delivery and ticked the necessary checkboxes. We are checking the Dockerfile and will get back to you on this.

2022-12-13 07:22 UTC, HeisenbergLin22 commented
> Thanks for the delivery @HeisenbergLin22. We'll look into it as soon as possible. In the meantime, could you please:
> 
> * Make sure you're creating a new file for your delivery instead of modifying the template
> * Read your first comment above and tick all checkboxes that apply
> * Check your Dockerfile - the build is failing for me: [docker.txt](https://github.com/w3f/Grant-Milestone-Delivery/files/10208392/docker.txt)

We have also updated the Dockerfile. Please take a look and see whether it works for you now.

2022-12-13 13:10 UTC, HeisenbergLin22 commented
> Thanks. Could you please also fill out the [invoice form ](https://forms.gle/LSRr7PCjBpEbKGh89)and merge my [PR](https://github.com/FacelessProject/Faceless-Grant-Milestone2-Delivery/pull/1)? Someone else will look into your delivery again soon and test the Dockerfile.

Hey @alxs , already filled the invoice form and merged your pr. I look forward to the comments from you guys. Thx.

2022-12-13 16:15 UTC, alxs commented
@HeisenbergLin22 could you also move the delivery file into the `deliveries` folder?

2022-12-14 02:59 UTC, HeisenbergLin22 commented
> @HeisenbergLin22 could you also move the delivery file into the `deliveries` folder?

Sure, done.

2022-12-14 08:16 UTC, 0xCaso commented
Thanks @alxs for the fixes, and hi @HeisenbergLin22. I'm starting the evaluation, I'll write here if I need your help.

2022-12-14 10:22 UTC, 0xCaso commented
@HeisenbergLin22 before I publish my evaluation, I'd like to ask you if with "Client Modules", in the delivery, you mean the functions you included in the *faceless* pallet. Am I wrong, or is the difference between milestones 1 and 2 ""just"" the newly added functions in [/faceless-substrate-node/pallets/faceless/src/lib.rs](https://github.com/HeisenbergLin22/Faceless_milestone2_delivery/blob/main/faceless-substrate-node/pallets/faceless/src/lib.rs), with the relative front-end part? Am I missing anything else?

2022-12-14 13:07 UTC, HeisenbergLin22 commented
> @HeisenbergLin22 before I publish my evaluation, I'd like to ask you if with "Client Modules", in the delivery, you mean the functions you included in the _faceless_ pallet. Am I wrong, or is the difference between milestones 1 and 2 ""just"" the newly added functions in [/faceless-substrate-node/pallets/faceless/src/lib.rs](https://github.com/HeisenbergLin22/Faceless_milestone2_delivery/blob/main/faceless-substrate-node/pallets/faceless/src/lib.rs), with the relative front-end part? Am I missing anything else?

Hey @0xCaso , you are exactly right. The main difference is the newly added functions in [/faceless-substrate-node/pallets/faceless/src/lib.rs](https://github.com/HeisenbergLin22/Faceless_milestone2_delivery/blob/main/faceless-substrate-node/pallets/faceless/src/lib.rs), with the relative front-end part, which is how we defined the milestone 2 delivery in our original [proposal](https://github.com/HeisenbergLin22/Grants-Program/blob/master/faceless.md).

2022-12-14 13:22 UTC, 0xCaso requested changes
Thanks @HeisenbergLin22 for the confirm. I've just pushed my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/e47803f5477318b5ee56a9035920bb88d9207235/evaluations/faceless_2_0xCaso.md). Let me know if you have any question!

2022-12-15 10:59 UTC, traklcoin commented
> Thanks @HeisenbergLin22 for the confirm. I've just pushed my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/e47803f5477318b5ee56a9035920bb88d9207235/evaluations/faceless_2_0xCaso.md). Let me know if you have any question!

Thanks for your comments. Will get back to you on this soon.

2022-12-15 11:00 UTC, HeisenbergLin22 commented
> Thanks @HeisenbergLin22 for the confirm. I've just pushed my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/e47803f5477318b5ee56a9035920bb88d9207235/evaluations/faceless_2_0xCaso.md). Let me know if you have any question!

Thanks for your comments. Will get back to you on this soon.

2022-12-17 13:04 UTC, HeisenbergLin22 commented
> Thanks @HeisenbergLin22 for the confirm. I've just pushed my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/e47803f5477318b5ee56a9035920bb88d9207235/evaluations/faceless_2_0xCaso.md). Let me know if you have any question!

Hey @0xCaso , thanks for your evaluation. You can find our response to your evaluation in this [document](https://github.com/HeisenbergLin22/Milestone2_document/blob/main/Response_to_evaluation.md). Please let me know if you have any further questions.

2022-12-19 13:35 UTC, 0xCaso commented
Thanks a lot @HeisenbergLin22 for the changes and updates!
Everything looks pretty good. The only thing is that I can't register an account in the application, because during the registration phase I cannot select the right Country/Region for the phone number. Is there a way to bypass this?

2022-12-20 02:53 UTC, HeisenbergLin22 commented
> Thanks a lot @HeisenbergLin22 for the changes and updates! Everything looks pretty good. The only thing is that I can't register an account in the application, because during the registration phase I cannot select the right Country/Region for the phone number. Is there a way to bypass this?

Hey @0xCaso , thanks for your prompt response. Since this is a proof of concept, we don't provide the option of country/region code at the moment. But we will definitely take this into account in the next phase of product development. Thanks for your advice.

2022-12-20 08:15 UTC, 0xCaso commented
I was meaning that in the section of the screenshot I'm not able to choose my country because it does not appear, so I can't go on with the testing of the dapp:
<img width="611" alt="Screenshot 2022-12-20 at 09 14 06" src="https://user-images.githubusercontent.com/22419450/208616816-34952911-1924-4e66-9972-a6367e812f66.png">
So, is there a way to bypass this problem?

2022-12-20 08:35 UTC, HeisenbergLin22 commented
> I was meaning that in the section of the screenshot I'm not able to choose my country because it does not appear, so I can't go on with the testing of the dapp: <img alt="Screenshot 2022-12-20 at 09 14 06" width="611" src="https://user-images.githubusercontent.com/22419450/208616816-34952911-1924-4e66-9972-a6367e812f66.png"> So, is there a way to bypass this problem?

Oh, I see. Would you please try to choose the country code that is already on the list, say the American one, and then type a random mobile number? We haven't worked out the challenge and response system yet since it's not on the delivery list. All you need to do after typing the mobile number step is to type a random four-number code and pass the authentication step. That should allow you to register the mobile number successfully.

2022-12-20 08:41 UTC, 0xCaso commented
Thanks. I've just tried, but actually it doesn't work: after inserting the 4 numbers code, it comes back to the first registration page (with the "Add New Account" button)

2022-12-20 09:32 UTC, HeisenbergLin22 commented
> Thanks. I've just tried, but actually it doesn't work: after inserting the 4 numbers code, it comes back to the first registration page (with the "Add New Account" button)

Can you see the mobile number you input in the new HRI list? If it does appear in the updated list, then it means the registration is successful.

2022-12-20 09:36 UTC, 0xCaso commented
Actually no, it does not appear. I've just the @HelloHuman account, but I guess I can try to use that one

2022-12-20 09:45 UTC, HeisenbergLin22 commented
> here

I see, would you please confirm that you have run a local substrate node before starting to test the Faceless DApp as specified in this [link](https://github.com/HeisenbergLin22/Faceless_milestone2_delivery#faceless-dapp-test)?

2022-12-20 09:47 UTC, 0xCaso commented
For now I was trying with the deployed dapp, but I'll also try this part locally to check if it works here

2022-12-20 12:44 UTC, HeisenbergLin22 commented
> link

Any chance you could be more specific about how the test of, say deposit fails? Like the token amount under the chosen HRI does not update after the deposit?

2022-12-20 13:22 UTC, 0xCaso commented
For example, deposit function:
- I select the new registered user
- I select `Deposit`
- in the new page, instead of showing my tag, it shows @Hellohuman; btw, I select DOT and put 1 as `Amount` (also in this page is not clear from where do the funds come, as I'm connected with an Ethereum wallet but below it's shown the Polkadot address...), and press `Deposit`;
- it comes back to the previous page, `History` tab is loading but nothing happens.

2022-12-20 14:36 UTC, HeisenbergLin22 commented
> For example, deposit function:
> 
> * I select the new registered user;
> * I select `Deposit`;
> * in the new page, instead of showing my tag, it shows @hellohuman; btw, I select DOT and put 1 as `Amount` (also in this page is not clear from where do the funds come, as I'm connected with an Ethereum wallet but below it's shown the Polkadot address...), and press `Deposit`;
> * it comes back to the previous page, `History` tab is loading but nothing happens.

Hey @0xCaso , would you please confirm you have successfully run the local nodes? None of the problems you mentioned occurred during our own test. Maybe we can schedule a meeting to show you how these functions work? Please add my Element handle @hlin100:matrix.org so that we can schedule a meeting there. You can also send an email to my gmail: lornacrevelingwgo23@gmail.com. We can also schedule a meeting via email.

2022-12-20 16:21 UTC, 0xCaso commented
I'm sorry but I didn't see there was an error with the node, and it stopped producing blocks for some reason, you were right (maybe further on you could add something that tells that the dapp is not connected to a node). I'll try to see if I can reproduce the bug.

In the end, I managed to try `Register`, `Deposit` and `Withdraw`. With `Transfer`, the dapp reloads losing its current state values (and deleting the account previously created).

2022-12-21 03:06 UTC, HeisenbergLin22 commented
> I'm sorry but I didn't see there was an error with the node, and it stopped producing blocks for some reason, you were right (maybe further on you could add something that tells that the dapp is not connected to a node). I'll try to see if I can reproduce the bug.
> 
> In the end, I managed to try `Register`, `Deposit` and `Withdraw`. With `Transfer`, the dapp reloads losing its current state values (and deleting the account previously created). To reproduce:
> 
> * Go to `Transfer`;
> * Select `Mobile Phone`;
> * Press `Next`;
> * Select a Coin and put an Amount, then select `Mobile Phone` and press `Transfer`.

Hey @0xCaso , thanks for your info. It seems you might have skipped a step between "Select `Mobile Phone`" and "Press `Next`;", which is about inputting the receiver's user name and mpk (plz check the fig below). You can find the mpk on the downside of the webpage and you could use your own registered user name as the receiver, say, a mobile number like +1-352786901. 
![image](https://user-images.githubusercontent.com/101542941/208810736-6816592f-d278-4ac0-bcc9-b2ea50d08c09.png)

2022-12-21 08:09 UTC, 0xCaso commented
> Hey @0xCaso , thanks for your info. It seems you might have skipped a step in between "Select `Mobile Phone`" and "Press `Next`;", which is about inputting the receiver's user name and mpk (plz check the fig below). I have forgotten to mention this step in our current tutorial. Sorry about that. You can find the mpk on the downside of the webpage and you could use your own registered user name as the receiver, say, a mobile number like +1-352786901. 
> ![image](https://user-images.githubusercontent.com/101542941/208810736-6816592f-d278-4ac0-bcc9-b2ea50d08c09.png)

Actually i didnt skip it, it seemed to be not relevant as whatever input I insert, I'll always see the same @user as receiver of the transfer.

2022-12-21 10:51 UTC, HeisenbergLin22 commented
> > Hey @0xCaso , thanks for your info. It seems you might have skipped a step in between "Select `Mobile Phone`" and "Press `Next`;", which is about inputting the receiver's user name and mpk (plz check the fig below). I have forgotten to mention this step in our current tutorial. Sorry about that. You can find the mpk on the downside of the webpage and you could use your own registered user name as the receiver, say, a mobile number like +1-352786901.
> > ![image](https://user-images.githubusercontent.com/101542941/208810736-6816592f-d278-4ac0-bcc9-b2ea50d08c09.png)
> 
> Actually i didnt skip it, it seemed to be not relevant as whatever input I insert, I'll always see the same user as receiver of the transfer.

Would you please confirm that the receiver account you input has been registered beforehand? Thx.

2022-12-22 17:10 UTC, 0xCaso commented
> Would you please confirm that the receiver account you input has been registered beforehand? Thx.

I've retried inserting a registered account, but as I already said nothing changes: I keep see @Teatrrrraloo as receiver. I don't know if it's because of the MPK value (I can't understand what it is)

2022-12-23 04:48 UTC, HeisenbergLin22 commented
> link

Hey @0xCaso , you've actually successfully completed the transfer process. Please ignore @Teatrrrraloo, which is merely a placeholder. Please go ahead and click on "confirm". You won't receive any message after you click on "confirm". But if you go back to check your own account balance and also the receiver balance, you will find both have been updated accordingly. If you need more information on how transfer works, you could check the updated [readme](https://github.com/HeisenbergLin22/Faceless_milestone2_delivery/blob/main/README.md#step-2-play-with-the-faceless-dapp). Feel free to leave me a message if there is any other problem.

2022-12-23 10:46 UTC, 0xCaso commented
Thanks a lot for the Tutorial update. Following the described steps, I was able to complete the transfer. I'm updating the evaluation!

2022-12-23 11:17 UTC, 0xCaso approved these changes

2022-12-23 11:28 UTC, Noc2 approved these changes

2022-12-23 11:28 UTC, merged

2022-12-23 11:34 UTC, 0xCaso commented
I'm happy to let you know that the milestone 2 has been accepted, congrats!

Could you please resend the invoice with the VAT amount (that should be 0)?

2022-12-23 13:23 UTC, lornacrevelingwgo23 commented
> I'm happy to let you know that the milestone 2 has been accepted, congrats!
> 
> Could you please resend the invoice with the VAT amount (that should be 0)?

Thanks a lot. I've already updated the invoice. Please check if the new invoice works for you.

2022-12-23 13:26 UTC, HeisenbergLin22 commented
> I'm happy to let you know that the milestone 2 has been accepted, congrats!
> 
> Could you please resend the invoice with the VAT amount (that should be 0)?

Thanks a lot. Already updated the invoice. Please check if the latest invoice works for you.

2022-12-23 13:33 UTC, 0xCaso commented
> Thanks a lot. Already updated the invoice. Please check if the latest invoice works for you.

The invoice you've sent is identical to the first one (that we received on 13 Dec - same date, no VAT amount)

2022-12-23 14:15 UTC, HeisenbergLin22 commented
> > Thanks a lot. Already updated the invoice. Please check if the latest invoice works for you.
> 
> The invoice you've sent is identical to the first one (that we received on 13 Dec - same date, no VAT amount)

Sorry, might have updated it with the old file. The new invoice should have the updated date and the right VAT amount (right under Amount). Please check it out.

2022-12-23 14:19 UTC, 0xCaso commented
The date is changed, but still the only amount (visible in the PDF you've sent) is 20k DAI for the milestone, there isn't the VAT one

2022-12-23 14:33 UTC, HeisenbergLin22 commented
> The date is changed, but still the only amount (visible in the PDF you've sent) is 20k DAI for the milestone, there isn't the VAT one

I see. I've updated the invoice, which includes another two lines for VAT amount and the total amount respectively. Thx.

2022-12-23 14:36 UTC, 0xCaso commented
Thanks a lot, this time it should be perfect. I'm forwarding it internally, so please allow up to 14 days for the payment process.

2023-01-09 10:13 UTC, RouvenP commented
hi @HeisenbergLin22, we transferred the payment today.