Cogency-Milestone_2
w3f/Grant-Milestone-Delivery pull request #783
Opened 2023-03-02 17:19 UTC by CogencyWeb3

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x ] This pull request is being made by the same account as the accepted application.
- [x ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

2023-03-06 13:22 UTC, takahser requested changes

2023-03-06 13:22 UTC, takahser commented on deliveries/Cogency-Milestone_1.md
> +* **Application Document:** Web3 Media Pilot
Please add the link to the application here, that might fix the build

2023-03-06 13:22 UTC, takahser commented on deliveries/Cogency-Milestone_2.md
> +* **Application Document:** Web3 Media Pilot
Same for M2

2023-03-08 15:56 UTC, CogencyWeb3 commented
Hi all,

M1 was already merged into your master branch - https://github.com/CogencyWeb3/Grant-Milestone-Delivery/blob/master/deliveries/Cogency-Milestone_1.md

We agreed with DavidH (cc'd) that the application document wasn't needed.

Could you please confirm if all ok please?

Best,
Raúl.
________________________________
From: S E R A Y A ***@***.***>
Sent: Monday, March 6, 2023 1:22 PM
To: w3f/Grant-Milestone-Delivery ***@***.***>
Cc: Project Manager ***@***.***>; Author ***@***.***>
Subject: Re: [w3f/Grant-Milestone-Delivery] Cogency-Milestone_2 (PR #783)


@takahser requested changes on this pull request.

________________________________

In deliveries/Cogency-Milestone_1.md<https://github.com/w3f/Grant-Milestone-Delivery/pull/783#discussion_r1126406973>:

> @@ -0,0 +1,19 @@
+# Milestone Delivery :mailbox:
+
+**The [invoice form :pencil:](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform) has been filled out correctly for this milestone and the delivery is according to the official [milestone delivery guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).**
+
+* **Application Document:** Web3 Media Pilot


Please add the link to the application here, that might fix the build

________________________________

In deliveries/Cogency-Milestone_2.md<https://github.com/w3f/Grant-Milestone-Delivery/pull/783#discussion_r1126407491>:

> @@ -0,0 +1,24 @@
+# Milestone Delivery :mailbox:
+
+**The [invoice form :pencil:](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform) has been filled out correctly for this milestone and the delivery is according to the official [milestone delivery guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).**
+
+* **Application Document:** Web3 Media Pilot


Same for M2

—
Reply to this email directly, view it on GitHub<https://github.com/w3f/Grant-Milestone-Delivery/pull/783#pullrequestreview-1326224207>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3F2HWRCL4NFF6MR7UOQOELW2XQKFANCNFSM6AAAAAAVNU74JM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-09 12:35 UTC, takahser commented
@CogencyWeb3 sorry, I wasn't aware that it's a private application. I confirm that case my previous comments don't apply.

2023-03-09 12:35 UTC, takahser commented on deliveries/Cogency-Milestone_1.md
> +* **Application Document:** Web3 Media Pilot
Update: doesn't apply, since it's a private application

2023-03-09 12:35 UTC, takahser commented on deliveries/Cogency-Milestone_2.md
> +* **Application Document:** Web3 Media Pilot
Update: doesn't apply, since it's a private application

2023-03-09 15:37 UTC, randombishop commented
Hi @CogencyWeb3 thanks for the delivery and sorry for the delay in evaluating it - caused by a backlog.
Will start evaluating it today and get back to you asap with feedback.

2023-03-09 23:26 UTC, randombishop commented
First quick remark: can you please remove changes to milestone 1 delivery file in this PR. That one is already merged and should not be modified.

2023-03-09 23:26 UTC, randombishop commented
<img width="808" alt="Screenshot 2023-03-09 at 6 26 35 PM" src="https://user-images.githubusercontent.com/7156021/224183575-913a8f3b-2680-426d-82a4-9e4c1befc661.png">

2023-03-10 13:50 UTC, randombishop commented
Also @CogencyWeb3 , did you submit your invoice through this [form](https://forms.gle/LSRr7PCjBpEbKGh89)?

2023-03-13 09:31 UTC, randombishop commented
Hi @CogencyWeb3!

Happy to inform you that I accepted this delivery, you can find the evaluation here:
https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cogency_2_randombishop.md

But in order to proceed, I still need you please to remove the milestone1 file from this PR, and also submit your invoice.

Thank you!

2023-03-14 13:42 UTC, merged

2023-03-15 08:24 UTC, fededubbi commented
Hi @CogencyWeb3,

I noticed that on our billing address you put Baarerstrasses instead of Baarerstrasse.
Can you please change it and resend?

Many thanks,
Federica

2023-03-15 15:52 UTC, CogencyWeb3 commented
Hi Federica,

Thanks for flagging. That has been amended and I've uploaded a new version of the invoice. Please let me know if there are any other issues.

Raul, thanks for looping me in.

All best,
David

________________________________
From: Project Manager ***@***.***>
Sent: 15 March 2023 09:26
To: w3f/Grant-Milestone-Delivery ***@***.***>; w3f/Grant-Milestone-Delivery ***@***.***>
Cc: Mention ***@***.***>; David Tomchak ***@***.***>
Subject: Re: [w3f/Grant-Milestone-Delivery] Cogency-Milestone_2 (PR #783)

Hi All,

David, do you mind changing the address please? See below.

Separately, on the PR, I deleted M1 as requested, but now I can't see M1 on your master branch, just M2 - https://github.com/CogencyWeb3/Grant-Milestone-Delivery/tree/master/deliveries

Any advice?

Best,
Raúl.
________________________________
From: fededubbi ***@***.***>
Sent: Wednesday, March 15, 2023 8:24 AM
To: w3f/Grant-Milestone-Delivery ***@***.***>
Cc: Project Manager ***@***.***>; Mention ***@***.***>
Subject: Re: [w3f/Grant-Milestone-Delivery] Cogency-Milestone_2 (PR #783)


Hi @CogencyWeb3<https://github.com/CogencyWeb3>,

I noticed that on our billing address you put Baarerstrasses instead of Baarerstrasse.
Can you please change it and resend?

Many thanks,
Federica

—
Reply to this email directly, view it on GitHub<https://github.com/w3f/Grant-Milestone-Delivery/pull/783#issuecomment-1469556921>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3F2HWRT3PB2DB2TKC6FOULW4F4DHANCNFSM6AAAAAAVNU74JM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-15 16:44 UTC, fededubbi commented
Hi @CogencyWeb3,

The invoice is fine, but i have one question on the swift code, if i search for the swift code correspondent i found this one:
SRLGGB3L, while on your invoice it is stated this:  SRLGGB2L.
Could you please double check which one is the right one?

Many thanks,
Federica

2023-03-21 16:33 UTC, semuelle commented
ping @CogencyWeb3

2023-03-22 06:47 UTC, CogencyWeb3 commented
Hello Sebastian. What's up?

Can you please use ***@***.*** for contact?

All best,
David

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Sebastian Müller ***@***.***>
Sent: Tuesday, March 21, 2023 4:33 pm
To: w3f/Grant-Milestone-Delivery ***@***.***>
Cc: Project Manager ***@***.***>; Mention ***@***.***>
Subject: Re: [w3f/Grant-Milestone-Delivery] Cogency-Milestone_2 (PR #783)


ping @CogencyWeb3<https://github.com/CogencyWeb3>

—
Reply to this email directly, view it on GitHub<https://github.com/w3f/Grant-Milestone-Delivery/pull/783#issuecomment-1478184065>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A3F2HWS5HNRSCUHZD6DKYQTW5HJ4XANCNFSM6AAAAAAVNU74JM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>