M1: Substrate Tokenomics Survey
w3f/Grant-Milestone-Delivery pull request #841
Opened 2023-04-24 01:50 UTC by taqtiqa-mark

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1348

2023-04-24 10:03 UTC, semuelle commented
Thanks for the delivery, @taqtiqa-mark. We will look into it as soon as possible!

2023-04-24 10:05 UTC, semuelle commented on deliveries/tokeneconomics-survey-2022_1.md
> +* **Application Document:** [Tokeneconomics Survey 2022](https://github.com/w3f/Grants-Program/tree/master/applications/tokeneconomics-survey-2022.md).
```suggestion
* **Application Document:** [Tokeneconomics Survey 2022](https://github.com/w3f/Grants-Program/blob/master/applications/tokenomics-survey-2022.md).
```

2023-05-01 14:24 UTC, takahser requested changes
@taqtiqa-mark thanks for your patience. I took a look and added my [interim evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/531df91b38f8d02fc3b9285a201d84cc1d8df78f/evaluations/tokenomics-survey-2022_1_takahser.md). Feel free to have a look and let me know, in case you have any questions.

2023-05-01 22:01 UTC, taqtiqa-mark commented
Thanks for the prompt review and thoughtful feedback. Please note the W3F changed the required template partway through this application, and in response to this application.  I believe some of the issue raised (e.g. license) reflect the fact this is its first use.
I believe the following address the issues raised:

- 0a. | Copyright and Licenses: This is per the deliverables
- 0b. | Documentation/Tutorial: From the W3F research template:
> Ideally, we recommend the usage of LaTeX/Overleaf for article production and Docker files for software execution.
- 0d. Infrastructure:  The W3F template can (in future) link to the Overleaf offline instructions, rather then require everyone to duplicate this effort.  See 0b
- 0e.2  Section: Polkadot Parachains: Thanks for the feedback. This is a first draft and doesn't seem reasonable to block acceptance of the milestone delivery.

2023-05-02 13:47 UTC, takahser commented
@taqtiqa-mark, thank you for the feedback. You're right about _0a._, _0b._, and _0d._. I wasn't aware that these were recommended in the template. As for _0e.2_, I understand that it's a work in progress, and I look forward to your expansion on it in future milestones. Please keep in mind that for finalized chapters, higher standards will apply during the evaluation process for future deliveries.

2023-05-02 15:21 UTC, merged

2023-05-02 15:35 UTC, takahser commented
@taqtiqa-mark I can't find the invoice for this milestone. Have you submitted it?

2023-05-03 01:04 UTC, taqtiqa-mark commented
Unless I can invoice as an individual .... 

The invoice may take a while - my accountant is reorganizing the company to be used and this may take some time.  I wanted to deliver the milestones, and am happy to continue and defer payment until the company details are in hand.

Apologies for any inconvenience.

2023-05-03 08:10 UTC, takahser commented
@taqtiqa-mark okay that works, no problem. Just add a comment here and tag me once the invoice is ready so I can forward it to our finance department.

2024-01-16 11:43 UTC, semuelle commented
Hi @taqtiqa-mark, our finance team would like to wrap up 2023, so I would like to ask you to submit an invoice soon. If you have to change the benefiting entity of the grant, feel free to submit an amendment.

2024-05-28 21:48 UTC, takahser commented
@taqtiqa-mark reminder that the invoice still hasn't been filed. Until when can we expect it to be submitted?

2024-05-29 01:02 UTC, taqtiqa-mark commented
Apologies, this is still being setup. Progress has been made, but not completed. This is not is my hands but our tax year ends 30 June, and I hope this serves as a hard deadline.

2024-05-29 12:32 UTC, takahser commented
@taqtiqa-mark understood, thanks for the feedback.

2024-06-05 03:18 UTC, taqtiqa-mark commented
@takahser I've submitted the invoice for the 3 milestones. Thanks for your patience.

2024-06-07 03:27 UTC, takahser commented
@taqtiqa-mark thanks, it will take up to 2 weeks to process the invoice and initiate the payout.