Galaxy Evaluation Milestone 1
w3f/Grant-Milestone-Delivery pull request #851
Opened 2023-05-02 16:18 UTC by Ali-Usama

# External Evaluation Galaxy

The delivery is satisfactory and as per the application. However, some suggestions are mentioned in the evaluation and after that, it'll be considered as accepted.

Link to the application pull request: [Galaxy](https://github.com/w3f/Grants-Program/pull/1642)

2023-05-03 11:56 UTC, 7flash commented
> # External Evaluation Galaxy
> 
> The delivery is satisfactory and as per the application. However, some suggestions are mentioned in the evaluation and after that, it'll be considered as accepted.
> 
> Link to the application pull request: [Galaxy](https://github.com/w3f/Grants-Program/pull/1642)

Updated. Ready for evaluation.

2023-05-03 19:40 UTC, Ali-Usama commented
Thanks for the quick fixes, @7flash. I've updated my evaluation as well.

2023-05-05 10:09 UTC, semuelle requested changes
Thanks for the evaluation, @Ali-Usama. I had some questions about the delivery, so I'll wait for those to be resolved to merge this one. 

I also made some change suggestions to your evaluation sheet. Generally, we prefer to link to a specific version of a file or directory in these, because `HEAD` versions might change and not reflect what was reviewed in the future.

2023-05-17 08:39 UTC, semuelle commented on evaluations/galaxy_1_ali-usama.md
> +## Update 4th May 2023
```suggestion
## General Notes

## Update 17th May 2023
Added unit tests.

## Update 4th May 2023
```

2023-05-17 08:40 UTC, merged

2023-05-17 09:53 UTC, 7flash commented
Thanks @semuelle @Ali-Usama @keeganquigley @randombishop

Comments and questions received from you are highly appreciated, your well-written feedback continuously pushing project forwards, - thank you!

2023-06-02 07:29 UTC, RouvenP commented
hi @Ali-Usama we transferred the KSM yesterday