Update: external evaluation of Validated Streams milestone 2
w3f/Grant-Milestone-Delivery pull request #896
Opened 2023-06-26 13:07 UTC by arahangua

As all outstanding issues have been resolved, I would like to submit an updated evaluation for this [milestone](https://github.com/w3f/Grant-Milestone-Delivery/pull/881). 

Thanks!

2023-06-27 19:07 UTC, semuelle commented
Hi @arahangua. Thanks again for your work. I can confirm that all the issues are fixed and everything works as expected. I will merge your PR and forward your info for your KSM reward.

Nice work using commits to refer to files and ensuring that the tests are running. With regard to tarpaulin, I find the percentages it reports not quite reliable. There is a fair bit of code in a pallet that does not need to be tested, like weights. Looking at the raw numbers, the coverage for the pallet is closer to 50%. I'll make a change suggestion to reflect that. And, just to completeness: we like to leave initial feedback in the document and add updates chronologically. It's true that the previous evaluation can be read by going through the history of the evaluation file, but the process is a lot easier to track when it's all in one file.

2023-06-27 19:24 UTC, semuelle requested changes

2023-06-27 19:24 UTC, semuelle commented on evaluations/validated-streams_2_arahangua.md
> +| **0c.** | Testing and Testing Guide | <ul><li>[x] </li></ul> | [Running tests](https://github.com/comrade-coop/validated-streams/blob/6f9478b84ea5730fceaae50c04b62e1ecee88fed/README.md#testing) <br
```suggestion
| **0c.** | Testing and Testing Guide | <ul><li>[x] </li></ul> | [Running tests](https://github.com/comrade-coop/validated-streams/blob/6f9478b84ea5730fceaae50c04b62e1ecee88fed/README.md#testing) <br> [proofs](https://github.com/comrade-coop/validated-streams/blob/6f9478b84ea5730fceaae50c04b62e1ecee88fed/consensus/src/proofs/tests.rs) <br> [events](https://github.com/comrade-coop/validated-streams/blob/b5a9437b2e59881a64c63596ded9144f72a39ad5/consensus/src/events/tests.rs) <br> [pallet](https://github.com/comrade-coop/validated-streams/blob/a8a55ab7f2f16401c8aefefccdcdfa4638ddb39a/pallet/src/tests.rs) | <ul><li> with 'on-chain proofs' : `cargo tarpaulin` reports ~60% test coverage for 'consensus' crate with 19 tests and ~70% coverage for 'pallet' crate with 8 tests. </li></ul><ul><li> Without 'on-chain proofs': `cargo tarpaulin` reports ~60% test coverage for the 'consensus' crate with 19 tests and ~50% coverage for the 'pallet' with 3 tests. |
```

2023-06-27 19:24 UTC, semuelle commented on evaluations/validated-streams_2_arahangua.md
>  - **Previously successfully merged evaluation:** All by semuelle
```suggestion
- **Previously successfully merged evaluation:** none
```

2023-06-27 19:26 UTC, merged

2023-06-30 07:52 UTC, RouvenP commented
hi @arahangua we just transferred the KSM